#include "nyangine-std/base/base_arena.c"
#include "nyangine-std/base/base_args.c"
#include "nyangine-std/base/base_backtrace.c"
#include "nyangine-std/base/base_base64.c"
#include "nyangine-std/base/base_bench.c"
#include "nyangine-std/base/base_build.c"
#include "nyangine-std/base/base_ceiling.c"
#include "nyangine-std/base/base_clock.c"
#include "nyangine-std/base/base_clock_format.c"
#include "nyangine-std/base/base_clock_instant.c"
#include "nyangine-std/base/base_command.c"
#include "nyangine-std/base/base_compress.c"
#include "nyangine-std/base/base_crc.c"
// after the clock it reads and the random source its jitter comes from.
#include "nyangine-std/base/base_rate.c"
#include "nyangine-std/base/base_circuit.c"
// after base_rate, whose nya_backoff_ms it draws each retry's delay from.
#include "nyangine-std/base/base_reconnect.c"
// after base_rate too, whose nya_backoff_ms spaces its restarts.
#include "nyangine-std/base/base_supervisor.c"
#include "nyangine-std/base/base_error.c"
#include "nyangine-std/base/base_filesystem.c"
// after base_filesystem.c: the whole-file helpers are written over its handles.
#include "nyangine-std/base/base_file.c"
#include "nyangine-std/base/base_hash.c"
// after base_hash.c, whose inline hash it calls.
#include "nyangine-std/base/base_cache.c"
#include "nyangine-std/base/base_integrity.c"
#include "nyangine-std/base/base_lexer.c"
#include "nyangine-std/base/base_logging.c"
// after base_logging.c: a failed requirement crashes through nya_log_panic.
#include "nyangine-std/base/base_preflight.c"
#include "nyangine-std/base/base_object.c"
#include "nyangine-std/base/base_reflection.c"
#include "nyangine-std/base/base_path.c"
#include "nyangine-std/base/base_perf.c"
#include "nyangine-std/base/base_string.c"
#include "nyangine-std/base/base_socket.c"
#include "nyangine-std/base/base_thread.c"
#include "nyangine-std/base/base_types.c"
#include "nyangine-std/base/base_url.c"
// after base_types.c and the platform clock and filesystem it reads the build time through.
#include "nyangine-std/base/base_version.c"
#include "nyangine-std/base/base_watch.c"
