---@meta
--
-- GENERATED by src/build/pp/luabind.c from the @lua annotations in the engine headers. DO NYAT EDIT.
--
-- What a plugin may actually call is narrower than this: a binding is only registered when the
-- manifest asked for its permission and the game's build granted it. The permission is on every
-- entry below, so a call that is missing at runtime can be traced to the manifest that did not ask
-- for it. See src/nyangine/core/core_plugin.h.

---@class nya
nya = {}

nya.audio = {}
nya.entity = {}
nya.input = {}
nya.plugin = {}
nya.file = {}
nya.log = {}
nya.app = {}

---Starts `music_handle` on the music track, replacing whatever was playing.
---Needs NYA_PLUGIN_PERMISSION_AUDIO.
---@param music_handle string
---@param loop boolean
---@param fade_in_ms integer
function nya.audio.play_music(music_handle, loop, fade_in_ms) end

---Stops the music, fading out over `fade_out_ms`.
---Needs NYA_PLUGIN_PERMISSION_AUDIO.
---@param fade_out_ms integer
function nya.audio.stop_music(fade_out_ms) end

---Pauses the music where it is.
---Needs NYA_PLUGIN_PERMISSION_AUDIO.
function nya.audio.pause_music() end

---Resumes it from there.
---Needs NYA_PLUGIN_PERMISSION_AUDIO.
function nya.audio.resume_music() end

---Whether the music track is sounding.
---Needs NYA_PLUGIN_PERMISSION_AUDIO.
---@return boolean
function nya.audio.music_playing() end

---Makes `child` follow `parent`, without moving it.
---Needs NYA_PLUGIN_PERMISSION_ENTITIES.
---@param child table
---@param parent table
---@return boolean
function nya.entity.parent_set(child, parent) end

---Unparents, keeping the world transform.
---Needs NYA_PLUGIN_PERMISSION_ENTITIES.
---@param child table
function nya.entity.parent_clear(child) end

---Whether `ancestor` is above `descendant`.
---Needs NYA_PLUGIN_PERMISSION_ENTITIES.
---@param ancestor table
---@param descendant table
---@return boolean
function nya.entity.is_ancestor(ancestor, descendant) end

---Rewrites `entity` and its subtree from their parents' transforms, now.
---Needs NYA_PLUGIN_PERMISSION_ENTITIES.
---@param entity table
function nya.entity.transform_sync(entity) end

---Removes an entity at the next simulation barrier, so iteration is never disturbed.
---Needs NYA_PLUGIN_PERMISSION_ENTITIES.
---@param entity table
function nya.entity.despawn(entity) end

---Whether the handle still resolves to a live entity.
---Needs NYA_PLUGIN_PERMISSION_ENTITIES.
---@param entity table
---@return boolean
function nya.entity.is_valid(entity) end

---How many entities are alive.
---Needs NYA_PLUGIN_PERMISSION_ENTITIES.
---@return integer
function nya.entity.count() end

---Drops every binding `action` has.
---Needs NYA_PLUGIN_PERMISSION_KEYBINDING.
---@param action integer
function nya.input.action_unbind(action) end

---Whether `action` has any key bound to it at all.
---Needs NYA_PLUGIN_PERMISSION_INPUT.
---@param action integer
---@return boolean
function nya.input.action_bound(action) end

---What `action` is called, or null when nothing has named it.
---Needs NYA_PLUGIN_PERMISSION_INPUT.
---@param action integer
---@return string
function nya.input.action_name(action) end

---The action called `name`, or NYA_INPUT_ACTION_NONE.
---Needs NYA_PLUGIN_PERMISSION_INPUT.
---@param name string
---@return integer
function nya.input.action_from_name(name) end

---True on the frame any of the action's bindings became satisfied.
---Needs NYA_PLUGIN_PERMISSION_INPUT.
---@param action integer
---@return boolean
function nya.input.action_just_pressed(action) end

---True while any of the action's bindings is satisfied.
---Needs NYA_PLUGIN_PERMISSION_INPUT.
---@param action integer
---@return boolean
function nya.input.action_pressed(action) end

---True on the frame the last of the action's bindings stopped being satisfied.
---Needs NYA_PLUGIN_PERMISSION_INPUT.
---@param action integer
---@return boolean
function nya.input.action_just_released(action) end

---The calling plugin's own name, as its directory spells it.
---Needs NYA_PLUGIN_PERMISSION_NONE.
---@return string
function nya.plugin.name() end

---Its version, from its manifest.
---Needs NYA_PLUGIN_PERMISSION_NONE.
---@return string
function nya.plugin.version() end

---Where it was loaded from.
---Needs NYA_PLUGIN_PERMISSION_NONE.
---@return string
function nya.plugin.directory() end

---Reads a file inside the plugin's own directory, or nil when there is none.
---Needs NYA_PLUGIN_PERMISSION_FILESYSTEM.
---@param path string
---@return string
function nya.file.read(path) end

---Writes one, and answers whether it worked.
---Needs NYA_PLUGIN_PERMISSION_FILESYSTEM.
---@param path string
---@param contents string
---@return boolean
function nya.file.write(path, contents) end

---One line in the engine log, marked as the script's.
---Needs NYA_PLUGIN_PERMISSION_NONE.
---@param text string
function nya.log.info(text) end

---The same at warning level.
---Needs NYA_PLUGIN_PERMISSION_NONE.
---@param text string
function nya.log.warn(text) end

---The same at error level.
---Needs NYA_PLUGIN_PERMISSION_NONE.
---@param text string
function nya.log.error(text) end

---Seconds since the application started.
---Needs NYA_PLUGIN_PERMISSION_NONE.
---@return number
function nya.app.time() end

---Spawns an entity from a table of `name`, `type`, `x`, `y` and `z`, and answers with its handle.
---Needs NYA_PLUGIN_PERMISSION_ENTITIES.
---@param options table
---@return table
function nya.entity.spawn(options) end

---Where an entity is, as a table of `x`, `y` and `z`, or nil once its handle no longer resolves.
---Needs NYA_PLUGIN_PERMISSION_ENTITIES.
---@param entity table
---@return table
function nya.entity.position(entity) end

---Tweens an entity to a point over `duration_s`.
---Needs NYA_PLUGIN_PERMISSION_ENTITIES.
---@param entity table
---@param x number
---@param y number
---@param z number
---@param duration_s number
function nya.entity.move_to(entity, x, y, z, duration_s) end

