#include "nyangine/base/base_arena.c"
#include "nyangine/base/base_args.c"
#include "nyangine/base/base_backtrace.c"
#include "nyangine/base/base_base64.c"
#include "nyangine/base/base_bench.c"
#include "nyangine/base/base_build.c"
#include "nyangine/base/base_ceiling.c"
#include "nyangine/base/base_clock.c"
#include "nyangine/base/base_clock_format.c"
#include "nyangine/base/base_clock_instant.c"
#include "nyangine/base/base_command.c"
#include "nyangine/base/base_compress.c"
#include "nyangine/base/base_crc.c"
#include "nyangine/base/base_error.c"
#include "nyangine/base/base_filesystem.c"
// after base_filesystem.c: the whole-file helpers are written over its handles.
#include "nyangine/base/base_file.c"
#include "nyangine/base/base_hash.c"
// after base_hash.c, whose inline hash it calls.
#include "nyangine/base/base_cache.c"
#include "nyangine/base/base_integrity.c"
#include "nyangine/base/base_lexer.c"
#include "nyangine/base/base_logging.c"
#include "nyangine/base/base_object.c"
#include "nyangine/base/base_reflection.c"
#include "nyangine/base/base_path.c"
#include "nyangine/base/base_perf.c"
#include "nyangine/base/base_string.c"
#include "nyangine/base/base_types.c"
#include "nyangine/base/base_url.c"
// after base_types.c and the platform clock and filesystem it reads the build time through.
#include "nyangine/base/base_version.c"
#include "nyangine/base/base_watch.c"
