/**
 * @file http_router.h
 *
 * Which handler answers a request, what runs around it, and what has to be true before it runs.
 *
 * ```
 * nya_http_router_find       the route for a method and a path, and whether the path exists at all
 * nya_http_router_check      whether a route table is well formed. Called for you by the server
 * nya_http_router_dispatch   runs the layers, the extractor and the handler, and answers
 *
 * nya_http_chain_next        a layer calls this to run the rest of the chain
 *
 * nya_http_response_problem  the error body every refusal here carries, negotiated HTML or JSON
 * nya_http_status_from_error the HTTP status an NYA_Error maps to
 * nya_http_response_error    answers with that status and a negotiated body, the message safe for it
 * ```
 *
 * The one layer the engine ships is `nya_http_layer_log`, and it lives in http_log.h with the levels
 * and the redaction that are most of what it is.
 *
 * ── a router per resource ──
 *
 * One file per resource, exporting its path constant and a router over a static route table, merged
 * at the root by the server. The table is data, so the OpenAPI document is generated by walking it
 * rather than by anybody writing the document down; see http_openapi.h.
 *
 * ```c
 * #define NYA_HTTP_METRICS_PATH "/api/metrics"
 *
 * NYA_INTERNAL const NYA_HttpRoute _ROUTES[] = {
 *     {
 *         .method        = NYA_HTTP_METHOD_QUERY,
 *         .path          = NYA_HTTP_METRICS_PATH,
 *         .auth          = NYA_HTTP_AUTH_NONE,
 *         .handler       = metrics_query,
 *         .summary       = "This program's frame time and ceilings",
 *         .response_type = nya_reflect_of(NYA_HttpMetricsDto),
 *         .statuses      = { NYA_HTTP_STATUS_OK, NYA_HTTP_STATUS_INTERNAL_ERROR },
 *     },
 * };
 * ```
 *
 * ── QUERY, POST, PUT, DELETE ──
 *
 * Those four are what a resource is written in: read, create, update, remove. A read is a QUERY
 * because a request here is a reflected DTO and a GET has nowhere to put one; see NYA_HttpMethod.
 *
 * GET is not gone and is not deprecated. It is parsed, routed and served, /docs and /openapi.json are
 * two GET routes and stay that way because a browser has no other verb, and a resource that answers a
 * read with no parameters at all is free to be one. What changed is which verb a new route reaches
 * for first. A HEAD with no HEAD route of its own answers from the GET, and from the QUERY when there
 * is no GET, with no body to carry a request document.
 *
 * nya_http_router_check refuses the two halves of getting this wrong: a `request_type` on a verb that
 * carries no body, and a 201 on a verb that changes nothing.
 *
 * ── preconditions are extractors ──
 *
 * A handler that needs a caller takes one:
 *
 * ```c
 * NYA_INTERNAL NYA_HttpStatus settings_put(NYA_HttpExchange* exchange, const NYA_HttpIdentity* identity);
 * ```
 *
 * and is registered in `handler_identified`, which nya_http_router_check requires `auth` to be set
 * for. There is no way to reach a NYA_HttpIdentifiedFn without the extractor having produced an
 * identity first, and no way to register one on a route that does not demand an identity: a handler
 * taking a caller cannot run unauthenticated, and the check is the type of the function pointer
 * rather than a rule anybody has to remember.
 *
 * The extractor is not a layer. A layer is cross-cutting and a program composes them; this is a
 * precondition of the route and runs after every layer and immediately before the handler, so a
 * logging layer still sees a 401 and a handler still cannot.
 *
 * ── layers ──
 *
 * An onion. A layer gets the exchange and the rest of the chain, does what it likes before calling
 * nya_http_chain_next, and sees the status on the way back out:
 *
 * ```c
 * NYA_HttpStatus my_layer(NYA_HttpExchange* exchange, NYA_HttpChain* next) {
 *     u64 started = nya_clock_get_monotonic_ns();
 *     NYA_HttpStatus status = nya_http_chain_next(exchange, next);
 *     nya_log_info("%llu ns", nya_clock_get_monotonic_ns() - started);
 *     return status;
 * }
 * ```
 *
 * A layer that returns without calling next answers on its own, which is what an authorization layer
 * does. Layers take no user data on purpose: one is installed by the program that also owns whatever
 * it would read, and a void pointer per layer is a lifetime question for no gain.
 *
 * ── every handler documents itself ──
 *
 * `auth`, `affinity`, `scope`, `summary`, `request_type`, `response_type` and `statuses` are not
 * documentation beside the code, they are the route. The OpenAPI document is generated from them, and in a debug
 * build an exchange that ends in a status its route did not list trips an assertion: a status list
 * that drifts from the code is caught by the test suite rather than by a reader of the schema.
 *
 * `statuses` covers the whole chain, so a route wrapped in a layer that can refuse declares that
 * refusal, and a route behind the extractor is required to declare 401 and 403 because the extractor
 * can produce them. The three server statuses, 500 and up, are exempt: they say this program is
 * broken, which is true of every route and is not a thing a schema usefully repeats.
 * */
#pragma once

#include "nyangine-std/base/base_arena.h"
#include "nyangine-std/base/base_attributes.h"
#include "nyangine-std/base/base_error.h"
#include "nyangine-std/base/base_reflection.h"
#include "nyangine-std/base/base_types.h"
#include "nyangine-core/http/http_auth.h"
#include "nyangine-core/http/http_cors.h"
#include "nyangine-core/http/http_message.h"
#include "nyangine-core/http/http_types.h"
#include "nyangine-core/permission/permission.h"

// CONSTANTS

/** Statuses one route may declare. Two successes and five refusals is past every route written so far. */
#define NYA_HTTP_MAX_STATUSES 8

/** Layers one router may carry, and the same again at the root. */
#define NYA_HTTP_MAX_LAYERS 8

/** Routers merged at the root: one per resource, so this is a count of resources. */
#define NYA_HTTP_MAX_ROUTERS 8

// TYPES

typedef enum NYA_HttpAuth       NYA_HttpAuth;
typedef enum NYA_HttpAffinity   NYA_HttpAffinity;
typedef struct NYA_HttpProblem  NYA_HttpProblem;
typedef struct NYA_HttpExchange NYA_HttpExchange;
typedef struct NYA_HttpChain    NYA_HttpChain;
typedef struct NYA_HttpRoute    NYA_HttpRoute;
typedef struct NYA_HttpRouter   NYA_HttpRouter;

/** What a route demands of its caller before the handler is reached. */
enum NYA_HttpAuth {
    /** Anyone who can open the port. What a read-only metrics page is, on a loopback bind. */
    NYA_HTTP_AUTH_NONE = 0,

    /** A JWT in `Authorization: Bearer`, verified against the server secret. */
    NYA_HTTP_AUTH_BEARER,
};

/**
 * Which thread a route's handler runs on once the server has workers; see http_server.h.
 *
 * It says nothing at all while `workers` is zero, where every handler runs on the thread that drains
 * the server, which is what it has always done.
 * */
enum NYA_HttpAffinity {
    /**
     * A worker thread, which is the default and what most handlers are.
     *
     * The handler may touch the exchange, its own arena, the request, the response, and state it owns
     * that is either immutable for the server's lifetime or made safe by itself. It may not touch the
     * program: no entities, no system registry, no renderer, no UI. That is not a request — base_thread.h's
     * nya_thread_main_only guards the modules that mean it, so a handler that gets this wrong crashes
     * there the first time it runs rather than corrupting a table once a month.
     * */
    NYA_HTTP_AFFINITY_WORKER = 0,

    /**
     * The thread that calls nya_system_http_tick, which for a program with a frame loop is the frame.
     *
     * The exchange is parsed, rate limited and bounded on the listener thread like any other, then
     * queued and answered inside the next tick, and handed back to the listener to write. That costs
     * it up to one frame of latency and it may hold the frame up for as long as it runs, which is the
     * trade a handler that reads or writes program state is making on purpose.
     * */
    NYA_HTTP_AFFINITY_MAIN,
};

// @reflect
/**
 * The body every refusal carries, so a client parses one shape whatever went wrong.
 *
 * A DTO like any other: the OpenAPI document describes it from this reflection, so the error schema
 * and the error body cannot disagree.
 * */
struct NYA_HttpProblem {
    /** The status, repeated in the body so a client that logged only the body still knows. */
    u32 status;

    /** The reason phrase: "Not Found", "Unauthorized". */
    char error[48];

    /** What specifically, in words, and never an internal detail a caller has no business with. */
    char detail[192];
};

/** One request being answered. Lives for exactly one exchange and is not referenced after it. */
struct NYA_HttpExchange {
    /** Parsed at the boundary. Never null inside a layer or a handler. */
    const NYA_HttpRequest* request;

    /** What the handler writes into. Never null. */
    NYA_HttpResponse* response;

    /** Which route matched. Null only inside a layer that ran before routing, which none currently do. */
    const NYA_HttpRoute* route;

    /**
     * Scratch for this exchange and nothing longer: it is emptied when the exchange ends, so anything
     * a handler wants to keep has to be copied into the response body before it returns.
     * */
    NYA_Arena* arena;

    /**
     * Who is calling, once the extractor has run. Only meaningful when `identified` is true, and a
     * handler never reads it directly: it is handed the identity as an argument or it is not called.
     * */
    NYA_HttpIdentity identity;
    b8               identified;

    /** The signing secret the extractor verifies against. Null when the server has none. */
    const u8* secret;
    u64       secret_size;

    /** Seconds since the epoch, read once, so every expiry check in one exchange agrees. */
    u64 now_s;

    /** Monotonic nanoseconds at the start of the exchange, for a layer that wants a duration. */
    u64 started_ns;

    /**
     * The peer as the socket reports it, in full. Never a forwarded header. What a security event keeps;
     * a request log truncates it with nya_http_address_truncate. "" when the exchange has no socket.
     * */
    NYA_ConstCString address;
};

/** A handler on a route that demands nothing of its caller. */
typedef NYA_HttpStatus (*NYA_HttpHandlerFn)(NYA_HttpExchange* exchange);

/**
 * A handler on a route that demands an identity. It is handed one, and see the file note for why it
 * cannot be registered anywhere that would not produce one.
 * */
typedef NYA_HttpStatus (*NYA_HttpIdentifiedFn)(NYA_HttpExchange* exchange, const NYA_HttpIdentity* identity);

/** One layer of the onion. See the file note. */
typedef NYA_HttpStatus (*NYA_HttpLayerFn)(NYA_HttpExchange* exchange, NYA_HttpChain* next);

/** Where a dispatch has got to in the layer chain. Opaque in practice: a layer only passes it along. */
struct NYA_HttpChain {
    const NYA_HttpLayerFn* layers;
    u32                    count;
    u32                    index;
};

/**
 * One path and one method, with everything true of it beside it.
 *
 * Plain data, so a resource's table is a `static const` array the compiler lays out and nothing
 * registers at startup.
 * */
struct NYA_HttpRoute {
    NYA_HttpMethod method;

    /**
     * The whole path, absolute and matched exactly: "/api/metrics". No patterns and no parameters.
     *
     * One verb per path per shape is what every resource here takes, with which instance being asked
     * for coming out of the request document a QUERY carries; a path pattern is a second way to say
     * the same thing and a second place for a traversal bug to live.
     * */
    NYA_ConstCString path;

    NYA_HttpAuth auth;

    /**
     * Which thread the handler, the extractor and this route's layers run on. Zero is a worker.
     *
     * The one thing about a route a reader cannot work out from the handler, and the one that is
     * expensive to get wrong, so it is declared beside `auth` rather than inferred.
     * */
    NYA_HttpAffinity affinity;

    /** Every bit the caller's identity has to carry. Only meaningful when `auth` is not _NONE. */
    NYA_HttpScope scope;

    /**
     * Every permission the caller has to hold in the table `nya_http_permissions_set` installed, checked
     * before the handler runs and answered with 403 when it does not.
     *
     * Zero is "any verified caller", which is what a route about the caller's own things takes. This is
     * not NYA_HttpScope: a scope is what the token says, and a permission is what the program's own
     * table says about whoever the token names, so taking a role away applies to the next request
     * rather than when a token expires. See permission.h.
     *
     * Only meaningful when `auth` is not _NONE: there is nobody to resolve for an unauthenticated route.
     * */
    NYA_Permission permission;

    /**
     * Which resource the permission is checked against — a room, a document, a guild.
     *
     * Zero is the program itself, which is what a route that is not about one particular thing takes.
     * A route whose resource comes out of the request sets `resource_of` instead.
     * */
    u64 resource;

    /**
     * Works out the resource from the request, for a route whose permission is about the thing being
     * asked for rather than about the program. Null means `resource` is used as it stands.
     *
     * It runs before the handler and before any body is read, so it reads the path and the query and
     * nothing else. Returning zero is "the program itself", the same as leaving both unset.
     * */
    u64 (*resource_of)(const NYA_HttpExchange* exchange);

    /** Set exactly when `auth` is NYA_HTTP_AUTH_NONE, unless `handler_callback` is set instead. */
    NYA_HttpHandlerFn handler;

    /** Set exactly when `auth` is not NYA_HTTP_AUTH_NONE, unless `handler_identified_callback` is set instead. */
    NYA_HttpIdentifiedFn handler_identified;

    /**
     * A reload-safe stand-in for `handler`: a token from `nya_callback(fn)`, resolved to the current
     * function on every dispatch through the resolver a program installs with nya_http_router_resolvers_set.
     *
     * A raw `handler` pointer is baked into the route table once and dangles the moment a code hot reload
     * swaps the DLL out from under it; a token survives, because the resolver re-derives it by name against
     * the new image (see [[code-hot-reload]]). Set this instead of `handler`, never both. Auth NONE only.
     * The http module holds only the opaque token — resolving it is the program's, since the named-callback
     * registry lives a layer above this one.
     * */
    u64 handler_callback;

    /** Likewise for `handler_identified`: a `nya_callback` token for an identified handler that hot-swaps. */
    u64 handler_identified_callback;

    /**
     * The CORS policy for this route, or null for the same-origin default. Overrides the router's own
     * `cors` when both are set, so a resource carries one policy and a route that differs states its own.
     * A browser calling this route from another origin reads its answer only through this; see http_cors.h.
     * */
    const NYA_HttpCors* cors;

    /** One line, for the OpenAPI summary. Required. */
    NYA_ConstCString summary;

    /** The paragraph under it, or null. */
    NYA_ConstCString description;

    /** The DTO the body must be, or null for a route that takes no body. */
    const NYA_TypeReflection* request_type;

    /** The DTO a success answers with, or null for a route that answers with nothing. */
    const NYA_TypeReflection* response_type;

    /**
     * Every status this route can answer with, the refusals included, ending at the first
     * NYA_HTTP_STATUS_NONE.
     *
     * The route's, not the handler's: a layer that answers on its own answers for this route, so what
     * it can produce belongs here too. In a debug build a status that is not in here is an assertion,
     * which is what stops the generated schema from describing a route that cannot refuse.
     * */
    NYA_HttpStatus statuses[NYA_HTTP_MAX_STATUSES];
};

/** One resource's routes, plus whatever wraps only them. */
struct NYA_HttpRouter {
    /** The OpenAPI tag these routes are grouped under: "metrics", "health". Required. */
    NYA_ConstCString name;

    const NYA_HttpRoute* routes;
    u32                  route_count;

    /** Layers around this resource's handlers only, outermost first. */
    const NYA_HttpLayerFn* layers;
    u32                    layer_count;

    /**
     * The CORS policy every route here takes unless it names its own, or null for the same-origin
     * default. One policy per resource is the common case; a route's own `cors` wins where they differ.
     * */
    const NYA_HttpCors* cors;
};

// FUNCTIONS

/**
 * Installs the table every route's `permission` is resolved against, and how a verified identity
 * becomes a subject in it.
 *
 * Both null is the default and means no route may demand a permission: a server that cannot resolve one
 * must refuse rather than pass, so a route declaring a permission answers 503 instead. That is the same
 * shape as a missing signing secret, and for the same reason.
 *
 * `subject_of` is the program's, because only the program knows what its subject ids are: a user row's
 * key, a peer index, a hash of the subject claim. Returning NYA_PERMISSION_SYSTEM is refused rather than
 * obeyed — that id answers yes to everything, and a token must never resolve to it.
 * */
NYA_API void nya_http_permissions_set(NYA_Permissions* permissions, u64 (*subject_of)(const NYA_HttpIdentity* identity));

/** The table in use, or null when none was installed. */
NYA_API NYA_Permissions* nya_http_permissions(void) __attr_no_discard;

/**
 * Whether `router` is a table this server will serve, and an error naming the offending route when it
 * is not: a missing path or summary, a path that is not absolute, a handler in the wrong slot for the
 * route's `auth`, a request DTO on a verb that carries no body, a 201 on a verb that changes nothing,
 * an empty status list, or a status the server cannot answer with.
 *
 * Called by nya_http_server_merge, and separately so a test can check a table without a socket.
 * */
NYA_API NYA_Error nya_http_router_check(const NYA_HttpRouter* router) __attr_no_discard;

/**
 * The route for `method` and `path`, or null.
 *
 * `out_path_exists` says whether any method is registered on that path, which is the difference
 * between 404 and 405. A HEAD with no HEAD route of its own falls back to the path's GET, and failing
 * that to its QUERY: a HEAD is a read whose body is dropped on the way out, and the two read verbs are
 * the ones it may be answered from. A QUERY answering a HEAD sees a request with no body.
 * */
NYA_API const NYA_HttpRoute*
nya_http_router_find(const NYA_HttpRouter* const* routers, u32 router_count, NYA_HttpMethod method, NYA_ConstCString path, OUT b8* out_path_exists)
    __attr_no_discard;

/**
 * Routes `exchange`, runs the root layers then the matched router's, then the extractor, then the
 * handler, and returns the status to answer with.
 *
 * Always answers: an unmatched path, a refused identity and a handler that returned an error status
 * all leave a NYA_HttpProblem in the response body, so there is no path out of here with a status and
 * an empty body a client has to guess about.
 * */
NYA_API NYA_HttpStatus nya_http_router_dispatch(
    NYA_HttpExchange*            exchange,
    const NYA_HttpRouter* const* routers,
    u32                          router_count,
    const NYA_HttpLayerFn*       layers,
    u32                          layer_count
);

/** Runs the rest of the chain. A layer that does not call this answers the request itself. */
NYA_API NYA_HttpStatus nya_http_chain_next(NYA_HttpExchange* exchange, NYA_HttpChain* chain);

/** Turns a route's `handler_callback` token into the function to call this dispatch. See nya_http_router_resolvers_set. */
typedef NYA_HttpHandlerFn (*NYA_HttpHandlerResolver)(u64 token);

/** Likewise for `handler_identified_callback`. */
typedef NYA_HttpIdentifiedFn (*NYA_HttpIdentifiedResolver)(u64 token);

/**
 * Installs how a `handler_callback` / `handler_identified_callback` token becomes a function pointer.
 *
 * The named-callback registry that survives a code reload is a layer above http, so the router cannot
 * resolve a token itself: a program wires this once at startup, each resolver a one-liner over
 * `nya_callback_get`. Until it is set, a route that carries a token asserts on dispatch rather than
 * guessing; routes that use the plain `handler`/`handler_identified` pointers need no resolver at all.
 * Either resolver may be null when that kind of token is never used.
 * */
NYA_API void nya_http_router_resolvers_set(NYA_HttpHandlerResolver handler, NYA_HttpIdentifiedResolver identified);

/**
 * Replaces the response body with a problem for `status`, in whichever of HTML and JSON the request's
 * Accept prefers: an escaped error page for a browser (Accept names text/html), the JSON NYA_HttpProblem
 * for everything else, which is what an API client and a wildcard Accept get.
 *
 * `detail` is shown to the caller, so it says what they did rather than what went wrong inside: "the
 * body is not JSON", never a file name or an internal error chain. It is escaped before it reaches the
 * HTML page, so a `<` in it is text and not a tag.
 * */
NYA_API NYA_HttpStatus nya_http_response_problem(NYA_HttpExchange* exchange, NYA_HttpStatus status, NYA_ConstCString detail);

/**
 * The HTTP status an NYA_Error's kind maps to: NYA_ERROR_NOT_FOUND is 404, an argument or a parse the
 * caller got wrong is 400, a denied permission is 403, an existing thing is 409, an unsupported one is
 * 501, a timeout is 503, and anything that says this program itself is broken is 500. NYA_ERROR_NONE,
 * which is not an error, is 200.
 *
 * The table a handler forwarding a call's failure would otherwise write by hand every time; see
 * nya_http_response_error.
 * */
NYA_API NYA_HttpStatus nya_http_status_from_error(NYA_ErrorKind kind) __attr_no_discard;

/**
 * Answers `exchange` with the status nya_http_status_from_error gives `error`, and a problem body
 * negotiated the same way nya_http_response_problem negotiates one.
 *
 * A 4xx carries `error`'s own message, which describes what the caller did; a 5xx never does, because
 * that message is about what broke inside and telling a stranger the shape of an internal failure only
 * helps them probe it — a 5xx says no more than its reason phrase. Pass an `error` that is `ok` and it
 * asserts: this is the failure path, and a success has a body of its own to write.
 *
 * The one line a handler returns when a call it forwarded failed:
 * `return nya_http_response_error(exchange, err);`
 * */
NYA_API NYA_HttpStatus nya_http_response_error(NYA_HttpExchange* exchange, NYA_Error error);
