/**
 * @file http_client.h
 *
 * Calling a route by its table entry: the request DTO in, the response DTO out, and nobody hand-builds
 * a URL or parses a body.
 *
 * ```
 * nya_http_client_call   one route, one request DTO, one response DTO, over any transport
 * ```
 *
 * The route table is already machine-readable — the OpenAPI document is generated by walking it, see
 * http_openapi.h — and this is the other reader of the same data. A route carries its method, its path,
 * its `request_type` and its `response_type`; given a value of the request type and somewhere to put the
 * response, this builds the request the server declared, sends it, and deserializes the answer into the
 * response type. The DTOs are the very ones the server's handler took and returned, so the two halves of
 * one call cannot drift: a field added to a DTO is sent and read on both sides without either being edited.
 *
 * ── the transport is a seam ──
 *
 * This module is rank 6 and the curl client is a plugin above it (see src/build/lint.c), so the caller
 * cannot reach down to a socket and must not try. Instead it assembles the request as bytes — a method, a
 * URL, a body and the two media types — and hands them to a NYA_HttpClientTransport the program supplies.
 * A program with the curl plugin wires a transport that performs the round trip over the network; a test
 * wires one that dispatches straight through nya_http_router_dispatch, with no socket at all, and exercises
 * the real server path against the real client path. The typed shape of the call is the same either way.
 *
 * ```c
 * MyRequestDto  request  = { .room = 3 };
 * MyResponseDto response  = { 0 };
 *
 * NYA_Error result = nya_http_client_call(arena, &transport, "http://localhost:8080", &ROUTES[0],
 *                                         &request, &response, nullptr);
 * if (!result.ok) nya_log_error("the call failed: %s", (NYA_ConstCString)result.message);
 * ```
 *
 * ── what an error is ──
 *
 * A transport failure, a status that is not a 2xx, and a body that does not fit the response DTO are all
 * errors, and none of them leaves a half-decoded value in the response: the response DTO is written only
 * once a 2xx body has parsed whole. A non-2xx carries the server's NYA_HttpProblem, which is parsed into the
 * result when it is asked for, so a caller reads *why* it was refused rather than only that it was.
 *
 * ── path parameters ──
 *
 * A route here is one absolute path matched exactly, with no `:param` or `{param}` segment: which instance
 * a request is about comes out of the request DTO a QUERY carries, not out of the path (see NYA_HttpRoute).
 * So the URL is `base_url` followed by the route's path verbatim, and there is nothing to bind. Should the
 * router ever grow path patterns, the binding — pulling a segment's value from a named field of the request
 * DTO by its reflection — belongs here, between building the URL and encoding the body.
 * */
#pragma once

#include "nyangine-std/base/base_arena.h"
#include "nyangine-std/base/base_attributes.h"
#include "nyangine-std/base/base_error.h"
#include "nyangine-std/base/base_reflection.h"
#include "nyangine-std/base/base_types.h"
#include "nyangine-core/http/http_router.h"
#include "nyangine-core/http/http_types.h"

// TYPES

typedef struct NYA_HttpClientWire      NYA_HttpClientWire;
typedef struct NYA_HttpClientReply     NYA_HttpClientReply;
typedef struct NYA_HttpClientTransport NYA_HttpClientTransport;
typedef struct NYA_HttpClientResult    NYA_HttpClientResult;

/**
 * The request as bytes, everything a transport needs and nothing it does not.
 *
 * The media types are the vocabulary enum rather than header text: a transport turns `content_type` and
 * `accept` into `Content-Type` and `Accept` with nya_http_media_type_text, so there is one place the header
 * text is spelled and a transport cannot announce a body it did not send.
 * */
struct NYA_HttpClientWire {
    NYA_HttpMethod method;

    /** The whole URL, `base_url` joined to the route's path. Never null. */
    NYA_ConstCString url;

    /** The serialized request DTO, or null for a route that takes no body. Not null terminated. */
    const u8* body;
    u64       body_size;

    /** What `body` is, NYA_HTTP_MEDIA_NONE when there is none. */
    NYA_HttpMediaType content_type;

    /** The format the response is asked for in, NYA_HTTP_MEDIA_NONE for a route that answers with nothing. */
    NYA_HttpMediaType accept;
};

/** What a transport fills in from the server's answer. */
struct NYA_HttpClientReply {
    /** The HTTP status, or zero when the transport got no reply at all — in which case it returns an error. */
    NYA_HttpStatus status;

    /** The response body, exactly as it arrived. May be null or empty. */
    const u8* body;
    u64       body_size;

    /**
     * What `Content-Type` announced, or NYA_HTTP_MEDIA_NONE when the transport could not tell. The caller
     * falls back to the format it asked for, and then to JSON, so a transport that leaves this unset still
     * decodes a reply in the negotiated format.
     * */
    NYA_HttpMediaType media_type;
};

/**
 * Performs one round trip: sends `wire` and fills `out_reply`.
 *
 * Returns an error only for a transport failure that produced no reply — a refused connection, a timeout.
 * A reply that arrived is a success here whatever its status: a 404 is an answer, and it is the caller of
 * nya_http_client_call, not the transport, that decides a non-2xx is an error. `arena` is scratch the
 * transport may allocate the reply body from; it outlives the call.
 * */
typedef NYA_Error (*NYA_HttpClientTransportFn)(void* userdata, const NYA_HttpClientWire* wire, NYA_Arena* arena, OUT NYA_HttpClientReply* out_reply);

/** How a call reaches the server, supplied by the program. */
struct NYA_HttpClientTransport {
    NYA_HttpClientTransportFn perform;

    /** Handed back to `perform` untouched: a curl handle, a loopback router table, whatever it needs. */
    void* userdata;

    /**
     * The wire format for both the request body and the response the call asks for. NYA_HTTP_MEDIA_NONE is
     * JSON, which is what an integration that has never heard of this engine speaks. NYA_HTTP_MEDIA_NYA and
     * NYA_HTTP_MEDIA_NYA_BINARY are what two nyangine programs use between themselves; binary carries the
     * DTO's layout hash, so a mismatched build is refused rather than read into the wrong fields.
     * */
    NYA_HttpMediaType format;
};

/** What a call reports beside the response DTO, for a caller that wants the status or the refusal. Optional. */
struct NYA_HttpClientResult {
    /** The status the server answered with, or zero when the transport got no reply. */
    NYA_HttpStatus status;

    /** Whether `problem` was filled: true when a non-2xx carried a NYA_HttpProblem body that parsed. */
    b8 problem_parsed;

    /** The server's error body, meaningful only when `problem_parsed`. */
    NYA_HttpProblem problem;
};

// FUNCTIONS

/**
 * Calls `route` on the server at `base_url` with `request_dto`, and writes the answer into `out_response_dto`.
 *
 * `request_dto` is a value of the route's `request_type`, or null when the route declares no request body;
 * `out_response_dto` is somewhere to write a value of the route's `response_type`, or null when the route
 * answers with nothing. Both are the reflected DTO types the server's own handler uses, which is the point:
 * the request is encoded through `request_type`'s reflection and the response decoded through
 * `response_type`'s, so this and the server agree by construction.
 *
 * `out_result` may be null. When it is not, it always carries the status, and carries the parsed
 * NYA_HttpProblem for a non-2xx that sent one.
 *
 * Returns NYA_ERROR_INVALID_ARGUMENT for a request that does not match the route (a body where the route
 * takes none, or the reverse), the transport's own error for a round trip that never got a reply,
 * NYA_ERROR_NOT_OK for a status that is not a 2xx, and NYA_ERROR_PARSE for a 2xx whose body does not fit the
 * response DTO. `out_response_dto` is written only on a clean success, so a failure never leaves a
 * half-decoded value there.
 * */
NYA_API NYA_Error nya_http_client_call(
    NYA_Arena*                     arena,
    const NYA_HttpClientTransport* transport,
    NYA_ConstCString               base_url,
    const NYA_HttpRoute*           route,
    const void*                    request_dto,
    OUT void*                      out_response_dto,
    OUT NYA_HttpClientResult*      out_result
) __attr_no_discard;
