/*
 * GENERATED by src/build/pp/watch.c from the @watch annotations in src/gnyame/robots.c. DO NYAT EDIT.
 *
 * Included by that file and by nothing else. Each macro is the body of one nya_watch() call: it
 * opens a frame, writes down every local it can reach from where the call sits, and ends the
 * frame in a defer, so every way out of the function unregisters what points into it.
 */
#pragma once

/* gny_robot_dqn_thrust (src/gnyame/robots.c:99) */
/* not watched: angle, declared below nya_watch(), so it is not in scope there (line 106) */
#define _nya_watch_gny_robot_dqn_thrust() \
    const u32 _nya_watch_frame = nya_watch_frame_begin(); \
    nya_watch_record(_nya_watch_frame, "gny_robot_dqn_thrust", "action", "u32", _nya_watch_type_of(action), (u32)sizeof(typeof(action)), &action); \
    defer nya_watch_frame_end(_nya_watch_frame)
