/*
 * GENERATED by src/build/pp/watch.c from the @watch annotations in src/gnyame/layers/layer_cube3d_stones.c. DO NYAT EDIT.
 *
 * Included by that file and by nothing else. Each macro is the body of one nya_watch() call: it
 * opens a frame, writes down every local it can reach from where the call sits, and ends the
 * frame in a defer, so every way out of the function unregisters what points into it.
 */
#pragma once

/* _gny_cube3d_stone_build (src/gnyame/layers/layer_cube3d_stones.c:344) */
/* not watched: cap, declared below nya_watch(), so it is not in scope there (line 383) */
#define _nya_watch__gny_cube3d_stone_build() \
    const u32 _nya_watch_frame = nya_watch_frame_begin(); \
    nya_watch_record(_nya_watch_frame, "_gny_cube3d_stone_build", "out", "NYA_Vertex3D*", _nya_watch_type_of(out), (u32)sizeof(typeof(out)), &out); \
    nya_watch_record(_nya_watch_frame, "_gny_cube3d_stone_build", "sides", "u32", _nya_watch_type_of(sides), (u32)sizeof(typeof(sides)), &sides); \
    nya_watch_record(_nya_watch_frame, "_gny_cube3d_stone_build", "segments", "u32", _nya_watch_type_of(segments), (u32)sizeof(typeof(segments)), &segments); \
    nya_watch_record(_nya_watch_frame, "_gny_cube3d_stone_build", "section", "const f32x2*", _nya_watch_type_of(section), (u32)sizeof(typeof(section)), &section); \
    nya_watch_record(_nya_watch_frame, "_gny_cube3d_stone_build", "at", "u32", _nya_watch_type_of(at), (u32)sizeof(typeof(at)), &at); \
    defer nya_watch_frame_end(_nya_watch_frame)
