/*
 * GENERATED by src/build/pp/watch.c from the @watch annotations in src/gnyame/agent.c. DO NYAT EDIT.
 *
 * Included by that file and by nothing else. Each macro is the body of one nya_watch() call: it
 * opens a frame, writes down every local it can reach from where the call sits, and ends the
 * frame in a defer, so every way out of the function unregisters what points into it.
 */
#pragma once

/* _gny_agent_observe (src/gnyame/agent.c:344) */
#define _nya_watch__gny_agent_observe() \
    const u32 _nya_watch_frame = nya_watch_frame_begin(); \
    nya_watch_record(_nya_watch_frame, "_gny_agent_observe", "session", "NYA_Session*", _nya_watch_type_of(session), (u32)sizeof(typeof(session)), &session); \
    nya_watch_record(_nya_watch_frame, "_gny_agent_observe", "out_senses", "OUT f32*", _nya_watch_type_of(out_senses), (u32)sizeof(typeof(out_senses)), &out_senses); \
    nya_watch_record(_nya_watch_frame, "_gny_agent_observe", "capacity", "u32", _nya_watch_type_of(capacity), (u32)sizeof(typeof(capacity)), &capacity); \
    nya_watch_record(_nya_watch_frame, "_gny_agent_observe", "episode", "GNY_AgentEpisode*", _nya_watch_type_of(episode), (u32)sizeof(typeof(episode)), &episode); \
    nya_watch_record(_nya_watch_frame, "_gny_agent_observe", "window", "NYA_Window*", _nya_watch_type_of(window), (u32)sizeof(typeof(window)), &window); \
    nya_watch_record(_nya_watch_frame, "_gny_agent_observe", "width", "f32", _nya_watch_type_of(width), (u32)sizeof(typeof(width)), &width); \
    nya_watch_record(_nya_watch_frame, "_gny_agent_observe", "height", "f32", _nya_watch_type_of(height), (u32)sizeof(typeof(height)), &height); \
    nya_watch_record(_nya_watch_frame, "_gny_agent_observe", "pointer", "f32x2", _nya_watch_type_of(pointer), (u32)sizeof(typeof(pointer)), &pointer); \
    defer nya_watch_frame_end(_nya_watch_frame)
