/*
 * GENERATED by src/build/pp/watch.c from the @watch annotations in src/gnyame/layers/layer_cube3d_features.c. DO NYAT EDIT.
 *
 * Included by that file and by nothing else. Each macro is the body of one nya_watch() call: it
 * opens a frame, writes down every local it can reach from where the call sits, and ends the
 * frame in a defer, so every way out of the function unregisters what points into it.
 */
#pragma once

/* _gny_cube3d_feature_column (src/gnyame/layers/layer_cube3d_features.c:136) */
#define _nya_watch__gny_cube3d_feature_column() \
    const u32 _nya_watch_frame = nya_watch_frame_begin(); \
    nya_watch_record(_nya_watch_frame, "_gny_cube3d_feature_column", "ui", "NYA_UI*", _nya_watch_type_of(ui), (u32)sizeof(typeof(ui)), &ui); \
    nya_watch_record(_nya_watch_frame, "_gny_cube3d_feature_column", "window", "NYA_Window*", _nya_watch_type_of(window), (u32)sizeof(typeof(window)), &window); \
    nya_watch_record(_nya_watch_frame, "_gny_cube3d_feature_column", "id", "NYA_ConstCString", _nya_watch_type_of(id), (u32)sizeof(typeof(id)), &id); \
    nya_watch_record(_nya_watch_frame, "_gny_cube3d_feature_column", "first", "u32", _nya_watch_type_of(first), (u32)sizeof(typeof(first)), &first); \
    nya_watch_record(_nya_watch_frame, "_gny_cube3d_feature_column", "end", "u32", _nya_watch_type_of(end), (u32)sizeof(typeof(end)), &end); \
    nya_watch_record(_nya_watch_frame, "_gny_cube3d_feature_column", "switches", "NYA_RenderToggle*", _nya_watch_type_of(switches), (u32)sizeof(typeof(switches)), &switches); \
    defer nya_watch_frame_end(_nya_watch_frame)
