/*
 * GENERATED by src/nyangine-build/pp/watch.c from the @watch annotations in tests/nyangine/debug/test_crash_report.c. DO NYAT EDIT.
 *
 * Included by that file and by nothing else. Each macro is the body of one nya_watch() call: it
 * opens a frame, writes down every local it can reach from where the call sits, and ends the
 * frame in a defer, so every way out of the function unregisters what points into it.
 */
#pragma once

/* child_stone_face (tests/nyangine/debug/test_crash_report.c:84) */
#define _nya_watch_child_stone_face() \
    const u32 _nya_watch_frame = nya_watch_frame_begin(); \
    nya_watch_record(_nya_watch_frame, "child_stone_face", "at", "u32", _nya_watch_type_of(at), (u32)sizeof(typeof(at)), &at); \
    nya_watch_record(_nya_watch_frame, "child_stone_face", "wanted", "u32", _nya_watch_type_of(wanted), (u32)sizeof(typeof(wanted)), &wanted); \
    nya_watch_record(_nya_watch_frame, "child_stone_face", "emitted", "u32", _nya_watch_type_of(emitted), (u32)sizeof(typeof(emitted)), &emitted); \
    defer nya_watch_frame_end(_nya_watch_frame)

/* child_stone_row (tests/nyangine/debug/test_crash_report.c:95) */
#define _nya_watch_child_stone_row() \
    const u32 _nya_watch_frame = nya_watch_frame_begin(); \
    nya_watch_record(_nya_watch_frame, "child_stone_row", "sides", "u32", _nya_watch_type_of(sides), (u32)sizeof(typeof(sides)), &sides); \
    nya_watch_record(_nya_watch_frame, "child_stone_row", "segments", "u32", _nya_watch_type_of(segments), (u32)sizeof(typeof(segments)), &segments); \
    nya_watch_record(_nya_watch_frame, "child_stone_row", "shape", "NYA_ConstCString", _nya_watch_type_of(shape), (u32)sizeof(typeof(shape)), &shape); \
    nya_watch_record(_nya_watch_frame, "child_stone_row", "at", "u32", _nya_watch_type_of(at), (u32)sizeof(typeof(at)), &at); \
    defer nya_watch_frame_end(_nya_watch_frame)
