/*
 * GENERATED by src/nyangine-build/pp/luabind.c from the @lua annotations in the engine headers. DO NYAT EDIT.
 *
 * Included by src/nyangine/plugins/lua/lua_engine.c, after the marshalling helpers it calls and the
 * _NYA_LuaBindingEntry it fills in. One function per binding, and one table for them all.
 */

NYA_INTERNAL void _nya_lua_bind_nya_audio_play_music(NYA_LuaCall* call) {
    NYA_ConstCString music_handle = _nya_lua_argument_string(call, 0);
    b8 loop = _nya_lua_argument_boolean(call, 1, false);
    u32 fade_in_ms = (u32)_nya_lua_argument_number(call, 2, 0.0);

    nya_audio_play_music(music_handle, loop, fade_in_ms);
}

NYA_INTERNAL void _nya_lua_bind_nya_audio_stop_music(NYA_LuaCall* call) {
    u32 fade_out_ms = (u32)_nya_lua_argument_number(call, 0, 0.0);

    nya_audio_stop_music(fade_out_ms);
}

NYA_INTERNAL void _nya_lua_bind_nya_audio_pause_music(NYA_LuaCall* call) {
    nya_unused(call);

    nya_audio_pause_music();
}

NYA_INTERNAL void _nya_lua_bind_nya_audio_resume_music(NYA_LuaCall* call) {
    nya_unused(call);

    nya_audio_resume_music();
}

NYA_INTERNAL void _nya_lua_bind_nya_audio_music_playing(NYA_LuaCall* call) {
    b8 result = nya_audio_music_playing();

    call->results[0]   = nya_lua_boolean(result);
    call->result_count = 1;
}

NYA_INTERNAL void _nya_lua_bind_nya_entity_parent_set(NYA_LuaCall* call) {
    NYA_EntityHandle child = _nya_lua_argument_handle(call, 0);
    NYA_EntityHandle parent = _nya_lua_argument_handle(call, 1);

    b8 result = nya_entity_parent_set(child, parent);

    call->results[0]   = nya_lua_boolean(result);
    call->result_count = 1;
}

NYA_INTERNAL void _nya_lua_bind_nya_entity_parent_clear(NYA_LuaCall* call) {
    NYA_EntityHandle child = _nya_lua_argument_handle(call, 0);

    nya_entity_parent_clear(child);
}

NYA_INTERNAL void _nya_lua_bind_nya_entity_is_ancestor(NYA_LuaCall* call) {
    NYA_EntityHandle ancestor = _nya_lua_argument_handle(call, 0);
    NYA_EntityHandle descendant = _nya_lua_argument_handle(call, 1);

    b8 result = nya_entity_is_ancestor(ancestor, descendant);

    call->results[0]   = nya_lua_boolean(result);
    call->result_count = 1;
}

NYA_INTERNAL void _nya_lua_bind_nya_entity_transform_sync(NYA_LuaCall* call) {
    NYA_EntityHandle entity = _nya_lua_argument_handle(call, 0);

    nya_entity_transform_sync(entity);
}

NYA_INTERNAL void _nya_lua_bind_nya_entity_despawn_deferred(NYA_LuaCall* call) {
    NYA_EntityHandle entity = _nya_lua_argument_handle(call, 0);

    nya_entity_despawn_deferred(entity);
}

NYA_INTERNAL void _nya_lua_bind_nya_entity_is_valid(NYA_LuaCall* call) {
    NYA_EntityHandle entity = _nya_lua_argument_handle(call, 0);

    b8 result = nya_entity_is_valid(entity);

    call->results[0]   = nya_lua_boolean(result);
    call->result_count = 1;
}

NYA_INTERNAL void _nya_lua_bind_nya_entity_count(NYA_LuaCall* call) {
    u32 result = nya_entity_count();

    call->results[0]   = nya_lua_number((f64)result);
    call->result_count = 1;
}

NYA_INTERNAL void _nya_lua_bind_nya_input_action_unbind(NYA_LuaCall* call) {
    NYA_InputAction action = (NYA_InputAction)(u32)_nya_lua_argument_number(call, 0, 0.0);

    nya_input_action_unbind(action);
}

NYA_INTERNAL void _nya_lua_bind_nya_input_action_bound(NYA_LuaCall* call) {
    NYA_InputAction action = (NYA_InputAction)(u32)_nya_lua_argument_number(call, 0, 0.0);

    b8 result = nya_input_action_bound(action);

    call->results[0]   = nya_lua_boolean(result);
    call->result_count = 1;
}

NYA_INTERNAL void _nya_lua_bind_nya_input_action_name(NYA_LuaCall* call) {
    NYA_InputAction action = (NYA_InputAction)(u32)_nya_lua_argument_number(call, 0, 0.0);

    NYA_ConstCString result = nya_input_action_name(action);

    call->results[0]   = nya_lua_string(result);
    call->result_count = 1;
}

NYA_INTERNAL void _nya_lua_bind_nya_input_action_from_name(NYA_LuaCall* call) {
    NYA_ConstCString name = _nya_lua_argument_string(call, 0);

    NYA_InputAction result = nya_input_action_from_name(name);

    call->results[0]   = nya_lua_number((f64)result);
    call->result_count = 1;
}

NYA_INTERNAL void _nya_lua_bind_nya_input_action_just_pressed(NYA_LuaCall* call) {
    NYA_InputAction action = (NYA_InputAction)(u32)_nya_lua_argument_number(call, 0, 0.0);

    b8 result = nya_input_action_just_pressed(action);

    call->results[0]   = nya_lua_boolean(result);
    call->result_count = 1;
}

NYA_INTERNAL void _nya_lua_bind_nya_input_action_pressed(NYA_LuaCall* call) {
    NYA_InputAction action = (NYA_InputAction)(u32)_nya_lua_argument_number(call, 0, 0.0);

    b8 result = nya_input_action_pressed(action);

    call->results[0]   = nya_lua_boolean(result);
    call->result_count = 1;
}

NYA_INTERNAL void _nya_lua_bind_nya_input_action_just_released(NYA_LuaCall* call) {
    NYA_InputAction action = (NYA_InputAction)(u32)_nya_lua_argument_number(call, 0, 0.0);

    b8 result = nya_input_action_just_released(action);

    call->results[0]   = nya_lua_boolean(result);
    call->result_count = 1;
}

/* Every generated binding, in one table. The hand written ones are in lua_engine.c beside it. */
NYA_INTERNAL const _NYA_LuaBindingEntry _NYA_LUA_GENERATED_BINDINGS[] = {
    { "nya.audio.play_music", _nya_lua_bind_nya_audio_play_music, NYA_PLUGIN_PERMISSION_AUDIO },
    { "nya.audio.stop_music", _nya_lua_bind_nya_audio_stop_music, NYA_PLUGIN_PERMISSION_AUDIO },
    { "nya.audio.pause_music", _nya_lua_bind_nya_audio_pause_music, NYA_PLUGIN_PERMISSION_AUDIO },
    { "nya.audio.resume_music", _nya_lua_bind_nya_audio_resume_music, NYA_PLUGIN_PERMISSION_AUDIO },
    { "nya.audio.music_playing", _nya_lua_bind_nya_audio_music_playing, NYA_PLUGIN_PERMISSION_AUDIO },
    { "nya.entity.parent_set", _nya_lua_bind_nya_entity_parent_set, NYA_PLUGIN_PERMISSION_ENTITIES },
    { "nya.entity.parent_clear", _nya_lua_bind_nya_entity_parent_clear, NYA_PLUGIN_PERMISSION_ENTITIES },
    { "nya.entity.is_ancestor", _nya_lua_bind_nya_entity_is_ancestor, NYA_PLUGIN_PERMISSION_ENTITIES },
    { "nya.entity.transform_sync", _nya_lua_bind_nya_entity_transform_sync, NYA_PLUGIN_PERMISSION_ENTITIES },
    { "nya.entity.despawn", _nya_lua_bind_nya_entity_despawn_deferred, NYA_PLUGIN_PERMISSION_ENTITIES },
    { "nya.entity.is_valid", _nya_lua_bind_nya_entity_is_valid, NYA_PLUGIN_PERMISSION_ENTITIES },
    { "nya.entity.count", _nya_lua_bind_nya_entity_count, NYA_PLUGIN_PERMISSION_ENTITIES },
    { "nya.input.action_unbind", _nya_lua_bind_nya_input_action_unbind, NYA_PLUGIN_PERMISSION_KEYBINDING },
    { "nya.input.action_bound", _nya_lua_bind_nya_input_action_bound, NYA_PLUGIN_PERMISSION_INPUT },
    { "nya.input.action_name", _nya_lua_bind_nya_input_action_name, NYA_PLUGIN_PERMISSION_INPUT },
    { "nya.input.action_from_name", _nya_lua_bind_nya_input_action_from_name, NYA_PLUGIN_PERMISSION_INPUT },
    { "nya.input.action_just_pressed", _nya_lua_bind_nya_input_action_just_pressed, NYA_PLUGIN_PERMISSION_INPUT },
    { "nya.input.action_pressed", _nya_lua_bind_nya_input_action_pressed, NYA_PLUGIN_PERMISSION_INPUT },
    { "nya.input.action_just_released", _nya_lua_bind_nya_input_action_just_released, NYA_PLUGIN_PERMISSION_INPUT },
};
