/* THIS FILE IS GENERATED. DO NYAT TOUCH. */

#pragma once

#include "nyangine/base/base_reflection.h"

/*
 * Generated by src/build/pp/reflection.c from the @reflect annotations under src/nyangine.
 *
 * Reach one of these through nya_reflect_of(TypeName) rather than by naming the symbol: the
 * macro is what makes a misspelling a link error instead of a null at runtime.
 */

/* ── primitives, defined in genyarated/reflection_engine.c ── */

extern const NYA_TypeReflection _NYA_REFLECT_b8;
extern const NYA_TypeReflection _NYA_REFLECT_b16;
extern const NYA_TypeReflection _NYA_REFLECT_b32;
extern const NYA_TypeReflection _NYA_REFLECT_b64;
extern const NYA_TypeReflection _NYA_REFLECT_u8;
extern const NYA_TypeReflection _NYA_REFLECT_u16;
extern const NYA_TypeReflection _NYA_REFLECT_u32;
extern const NYA_TypeReflection _NYA_REFLECT_u64;
extern const NYA_TypeReflection _NYA_REFLECT_s8;
extern const NYA_TypeReflection _NYA_REFLECT_s16;
extern const NYA_TypeReflection _NYA_REFLECT_s32;
extern const NYA_TypeReflection _NYA_REFLECT_s64;
extern const NYA_TypeReflection _NYA_REFLECT_f32;
extern const NYA_TypeReflection _NYA_REFLECT_f64;
extern const NYA_TypeReflection _NYA_REFLECT_char;
extern const NYA_TypeReflection _NYA_REFLECT_string;

extern const NYA_TypeReflection _NYA_REFLECT_f32x2;
extern const NYA_TypeReflection _NYA_REFLECT_f32x3;
extern const NYA_TypeReflection _NYA_REFLECT_f32x4;

/* ── annotated types ── */

extern const NYA_TypeReflection _NYA_REFLECT_NYA_AccountSession;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_AccountUser;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_AudioPass;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_AudioEqualizer;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_AudioCompressor;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_AudioEcho;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_AudioReverb;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_AudioLimiter;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_AudioEffects;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_AudioSpace;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_AudioPropagation;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_ConfigEngineRenderer;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_ConfigEnginePhysics;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_ConfigEngineAudio;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_ConfigEngine;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_ConfigDocument;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_EntityState;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_EntityVisualKind;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_PluginPermission;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_PluginDependency;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_PluginManifest;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_SceneVisual;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_SceneEntity;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_SettingsVolumes;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_GraphicsQuality;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_SettingsGraphics;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_HttpMetricsDto;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_HttpCeilingDto;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_HttpCeilingsDto;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_HttpArenaDto;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_HttpArenasDto;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_HttpOwnerDto;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_HttpSystemsDto;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_HttpAccountingDto;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_HttpScope;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_HttpIdentity;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_HttpLogLevel;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_HttpLogAddress;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_HttpLogConfig;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_HttpProblem;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_HttpTotpSubmission;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_HttpTotpRecoveryDto;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_HttpTotpEnrolmentDto;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_Quaternion;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_EaseType;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_NetPeerId;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_Light2D;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_Render3DFog;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_Render3DDecals;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_Color;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_RenderToggle;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_RenderFeatures;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_RenderOutput;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_PostInk;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_PostAmbientOcclusion;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_PostAntialias;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_PostFocus;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_PostDepthOfField;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_PostSpeedLines;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_PostBloom;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_PostEyeAdaptation;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_PostLightShafts;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_PostMotionBlur;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_PostDebugView;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_Render2DHaze;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_NetChatMessage;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_UIOverflow;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_UIStateColors;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_UISkin;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_UIStateSkins;
extern const NYA_TypeReflection _NYA_REFLECT_NYA_UIStyle;

/** Every annotated engine type. The game's are in genyarated/reflection.h. */
#define NYA_REFLECT_ENGINE_TYPE_COUNT 71

extern const NYA_TypeReflection* const NYA_REFLECT_ENGINE_TYPES[NYA_REFLECT_ENGINE_TYPE_COUNT];
