/**
 * @file http_router.h
 *
 * Which handler answers a request, what runs around it, and what has to be true before it runs.
 *
 * ```
 * nya_http_router_find       the route for a method and a path, and whether the path exists at all
 * nya_http_router_check      whether a route table is well formed. Called for you by the server
 * nya_http_router_dispatch   runs the layers, the extractor and the handler, and answers
 *
 * nya_http_chain_next        a layer calls this to run the rest of the chain
 *
 * nya_http_layer_log         the one layer the engine ships: a line per request, with its duration
 *
 * nya_http_response_problem  the error body every refusal here carries
 * ```
 *
 * ── a router per resource ──
 *
 * One file per resource, exporting its path constant and a router over a static route table, merged
 * at the root by the server. The table is data, so the OpenAPI document is generated by walking it
 * rather than by anybody writing the document down; see http_openapi.h.
 *
 * ```c
 * #define NYA_HTTP_METRICS_PATH "/api/metrics"
 *
 * NYA_INTERNAL const NYA_HttpRoute _ROUTES[] = {
 *     {
 *         .method        = NYA_HTTP_METHOD_GET,
 *         .path          = NYA_HTTP_METRICS_PATH,
 *         .auth          = NYA_HTTP_AUTH_NONE,
 *         .handler       = metrics_get,
 *         .summary       = "This program's frame time and ceilings",
 *         .response_type = nya_reflect_of(NYA_HttpMetricsDto),
 *         .statuses      = { NYA_HTTP_STATUS_OK, NYA_HTTP_STATUS_INTERNAL_ERROR },
 *     },
 * };
 * ```
 *
 * ── preconditions are extractors ──
 *
 * A handler that needs a caller takes one:
 *
 * ```c
 * NYA_INTERNAL NYA_HttpStatus settings_put(NYA_HttpExchange* exchange, const NYA_HttpIdentity* identity);
 * ```
 *
 * and is registered in `handler_identified`, which nya_http_router_check requires `auth` to be set
 * for. There is no way to reach a NYA_HttpIdentifiedFn without the extractor having produced an
 * identity first, and no way to register one on a route that does not demand an identity: a handler
 * taking a caller cannot run unauthenticated, and the check is the type of the function pointer
 * rather than a rule anybody has to remember.
 *
 * The extractor is not a layer. A layer is cross-cutting and a program composes them; this is a
 * precondition of the route and runs after every layer and immediately before the handler, so a
 * logging layer still sees a 401 and a handler still cannot.
 *
 * ── layers ──
 *
 * An onion. A layer gets the exchange and the rest of the chain, does what it likes before calling
 * nya_http_chain_next, and sees the status on the way back out:
 *
 * ```c
 * NYA_HttpStatus my_layer(NYA_HttpExchange* exchange, NYA_HttpChain* next) {
 *     u64 started = nya_clock_get_monotonic_ns();
 *     NYA_HttpStatus status = nya_http_chain_next(exchange, next);
 *     nya_log_info("%llu ns", nya_clock_get_monotonic_ns() - started);
 *     return status;
 * }
 * ```
 *
 * A layer that returns without calling next answers on its own, which is what an authorization layer
 * does. Layers take no user data on purpose: one is installed by the program that also owns whatever
 * it would read, and a void pointer per layer is a lifetime question for no gain.
 *
 * ── every handler documents itself ──
 *
 * `auth`, `scope`, `summary`, `request_type`, `response_type` and `statuses` are not documentation
 * beside the code, they are the route. The OpenAPI document is generated from them, and in a debug
 * build a handler that returns a status its route did not list trips an assertion: a status list that
 * drifts from the handler is caught by the test suite rather than by a reader.
 * */
#pragma once

#include "nyangine/base/base_arena.h"
#include "nyangine/base/base_attributes.h"
#include "nyangine/base/base_error.h"
#include "nyangine/base/base_reflection.h"
#include "nyangine/base/base_types.h"
#include "nyangine/http/http_auth.h"
#include "nyangine/http/http_message.h"
#include "nyangine/http/http_types.h"

/*
 * ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 * CONSTANTS
 * ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 */

/** Statuses one route may declare. Two successes and five refusals is past every route written so far. */
#define NYA_HTTP_MAX_STATUSES 8

/** Layers one router may carry, and the same again at the root. */
#define NYA_HTTP_MAX_LAYERS 8

/** Routers merged at the root: one per resource, so this is a count of resources. */
#define NYA_HTTP_MAX_ROUTERS 8

/*
 * ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 * TYPES
 * ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 */

typedef enum NYA_HttpAuth       NYA_HttpAuth;
typedef struct NYA_HttpProblem  NYA_HttpProblem;
typedef struct NYA_HttpExchange NYA_HttpExchange;
typedef struct NYA_HttpChain    NYA_HttpChain;
typedef struct NYA_HttpRoute    NYA_HttpRoute;
typedef struct NYA_HttpRouter   NYA_HttpRouter;

/** What a route demands of its caller before the handler is reached. */
enum NYA_HttpAuth {
    /** Anyone who can open the port. What a read-only metrics page is, on a loopback bind. */
    NYA_HTTP_AUTH_NONE = 0,

    /** A JWT in `Authorization: Bearer`, verified against the server secret. */
    NYA_HTTP_AUTH_BEARER,
};

// @reflect
/**
 * The body every refusal carries, so a client parses one shape whatever went wrong.
 *
 * A DTO like any other: the OpenAPI document describes it from this reflection, so the error schema
 * and the error body cannot disagree.
 * */
struct NYA_HttpProblem {
    /** The status, repeated in the body so a client that logged only the body still knows. */
    u32 status;

    /** The reason phrase: "Not Found", "Unauthorized". */
    char error[48];

    /** What specifically, in words, and never an internal detail a caller has no business with. */
    char detail[192];
};

/** One request being answered. Lives for exactly one exchange and is not referenced after it. */
struct NYA_HttpExchange {
    /** Parsed at the boundary. Never null inside a layer or a handler. */
    const NYA_HttpRequest* request;

    /** What the handler writes into. Never null. */
    NYA_HttpResponse* response;

    /** Which route matched. Null only inside a layer that ran before routing, which none currently do. */
    const NYA_HttpRoute* route;

    /**
     * Scratch for this exchange and nothing longer: it is emptied when the exchange ends, so anything
     * a handler wants to keep has to be copied into the response body before it returns.
     * */
    NYA_Arena* arena;

    /**
     * Who is calling, once the extractor has run. Only meaningful when `identified` is true, and a
     * handler never reads it directly: it is handed the identity as an argument or it is not called.
     * */
    NYA_HttpIdentity identity;
    b8               identified;

    /** The signing secret the extractor verifies against. Null when the server has none. */
    const u8* secret;
    u64       secret_size;

    /** Seconds since the epoch, read once, so every expiry check in one exchange agrees. */
    u64 now_s;

    /** Monotonic nanoseconds at the start of the exchange, for a layer that wants a duration. */
    u64 started_ns;
};

/** A handler on a route that demands nothing of its caller. */
typedef NYA_HttpStatus (*NYA_HttpHandlerFn)(NYA_HttpExchange* exchange);

/**
 * A handler on a route that demands an identity. It is handed one, and see the file note for why it
 * cannot be registered anywhere that would not produce one.
 * */
typedef NYA_HttpStatus (*NYA_HttpIdentifiedFn)(NYA_HttpExchange* exchange, const NYA_HttpIdentity* identity);

/** One layer of the onion. See the file note. */
typedef NYA_HttpStatus (*NYA_HttpLayerFn)(NYA_HttpExchange* exchange, NYA_HttpChain* next);

/** Where a dispatch has got to in the layer chain. Opaque in practice: a layer only passes it along. */
struct NYA_HttpChain {
    const NYA_HttpLayerFn* layers;
    u32                    count;
    u32                    index;
};

/**
 * One path and one method, with everything true of it beside it.
 *
 * Plain data, so a resource's table is a `static const` array the compiler lays out and nothing
 * registers at startup.
 * */
struct NYA_HttpRoute {
    NYA_HttpMethod method;

    /**
     * The whole path, absolute and matched exactly: "/api/metrics". No patterns and no parameters.
     *
     * One GET or POST per path, with the variant chosen by a query parameter that parses to an enum,
     * is the shape every resource here takes; a path pattern is a second way to say the same thing and
     * a second place for a traversal bug to live.
     * */
    NYA_ConstCString path;

    NYA_HttpAuth auth;

    /** Every bit the caller's identity has to carry. Only meaningful when `auth` is not _NONE. */
    NYA_HttpScope scope;

    /** Set exactly when `auth` is NYA_HTTP_AUTH_NONE. */
    NYA_HttpHandlerFn handler;

    /** Set exactly when `auth` is not NYA_HTTP_AUTH_NONE. */
    NYA_HttpIdentifiedFn handler_identified;

    /** One line, for the OpenAPI summary. Required. */
    NYA_ConstCString summary;

    /** The paragraph under it, or null. */
    NYA_ConstCString description;

    /** The DTO the body must be, or null for a route that takes no body. */
    const NYA_TypeReflection* request_type;

    /** The DTO a success answers with, or null for a route that answers with nothing. */
    const NYA_TypeReflection* response_type;

    /**
     * Every status this handler can produce, the refusals included, ending at the first
     * NYA_HTTP_STATUS_NONE. In a debug build a status that is not in here is an assertion.
     * */
    NYA_HttpStatus statuses[NYA_HTTP_MAX_STATUSES];
};

/** One resource's routes, plus whatever wraps only them. */
struct NYA_HttpRouter {
    /** The OpenAPI tag these routes are grouped under: "metrics", "health". Required. */
    NYA_ConstCString name;

    const NYA_HttpRoute* routes;
    u32                  route_count;

    /** Layers around this resource's handlers only, outermost first. */
    const NYA_HttpLayerFn* layers;
    u32                    layer_count;
};

/*
 * ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 * FUNCTIONS
 * ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 */

/**
 * Whether `router` is a table this server will serve, and an error naming the offending route when it
 * is not: a missing path or summary, a path that is not absolute, a handler in the wrong slot for the
 * route's `auth`, an empty status list, or a status the server cannot answer with.
 *
 * Called by nya_http_server_merge, and separately so a test can check a table without a socket.
 * */
NYA_API NYA_Error nya_http_router_check(const NYA_HttpRouter* router) __attr_no_discard;

/**
 * The route for `method` and `path`, or null.
 *
 * `out_path_exists` says whether any method is registered on that path, which is the difference
 * between 404 and 405. HEAD falls back to the GET route, since a HEAD is a GET whose body is dropped.
 * */
NYA_API const NYA_HttpRoute*
nya_http_router_find(const NYA_HttpRouter* const* routers, u32 router_count, NYA_HttpMethod method, NYA_ConstCString path, OUT b8* out_path_exists)
    __attr_no_discard;

/**
 * Routes `exchange`, runs the root layers then the matched router's, then the extractor, then the
 * handler, and returns the status to answer with.
 *
 * Always answers: an unmatched path, a refused identity and a handler that returned an error status
 * all leave a NYA_HttpProblem in the response body, so there is no path out of here with a status and
 * an empty body a client has to guess about.
 * */
NYA_API NYA_HttpStatus nya_http_router_dispatch(
    NYA_HttpExchange*            exchange,
    const NYA_HttpRouter* const* routers,
    u32                          router_count,
    const NYA_HttpLayerFn*       layers,
    u32                          layer_count
);

/** Runs the rest of the chain. A layer that does not call this answers the request itself. */
NYA_API NYA_HttpStatus nya_http_chain_next(NYA_HttpExchange* exchange, NYA_HttpChain* chain);

/**
 * One log line per request: method, path, status and how long the rest of the chain took.
 *
 * Outermost when a program installs it, so the duration is the whole exchange and the status is
 * whatever anything inside decided.
 * */
NYA_API NYA_HttpStatus nya_http_layer_log(NYA_HttpExchange* exchange, NYA_HttpChain* next);

/**
 * Replaces the response body with a NYA_HttpProblem for `status`.
 *
 * `detail` is shown to the caller, so it says what they did rather than what went wrong inside: "the
 * body is not JSON", never a file name or an internal error chain.
 * */
NYA_API NYA_HttpStatus nya_http_response_problem(NYA_HttpExchange* exchange, NYA_HttpStatus status, NYA_ConstCString detail);
