#include "nyangine/base/base.c"
#include "nyangine/core/core.c"
#include "nyangine/math/math.c"
#include "nyangine/nn/nn.c"
#include "nyangine/platform/platform.c"
#include "nyangine/renderer/renderer.c"
#include "nyangine/ui/ui.c"
