/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 61
#define LARGE_STATE_COUNT 24
#define SYMBOL_COUNT 59
#define ALIAS_COUNT 0
#define TOKEN_COUNT 45
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_nya = 2,
  anon_sym_object = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_COLON = 6,
  anon_sym_SEMI = 7,
  anon_sym_LBRACK = 8,
  anon_sym_RBRACK = 9,
  anon_sym_any = 10,
  anon_sym_null = 11,
  anon_sym_COMMA = 12,
  anon_sym_true = 13,
  anon_sym_false = 14,
  anon_sym_DQUOTE = 15,
  aux_sym_string_token1 = 16,
  sym_escape_sequence = 17,
  sym_number = 18,
  anon_sym_void = 19,
  anon_sym_b8 = 20,
  anon_sym_b16 = 21,
  anon_sym_b32 = 22,
  anon_sym_b64 = 23,
  anon_sym_b128 = 24,
  anon_sym_u8 = 25,
  anon_sym_u16 = 26,
  anon_sym_u32 = 27,
  anon_sym_u64 = 28,
  anon_sym_u128 = 29,
  anon_sym_s8 = 30,
  anon_sym_s16 = 31,
  anon_sym_s32 = 32,
  anon_sym_s64 = 33,
  anon_sym_s128 = 34,
  anon_sym_f16 = 35,
  anon_sym_f32 = 36,
  anon_sym_f64 = 37,
  anon_sym_f128 = 38,
  anon_sym_char = 39,
  anon_sym_wchar = 40,
  anon_sym_string = 41,
  anon_sym_wstring = 42,
  anon_sym_array = 43,
  sym_comment = 44,
  sym_document = 45,
  sym_header = 46,
  sym_object = 47,
  sym_member = 48,
  sym__value = 49,
  sym_scalar = 50,
  sym_array = 51,
  sym_boolean = 52,
  sym_null = 53,
  sym_string = 54,
  sym_type = 55,
  aux_sym_object_repeat1 = 56,
  aux_sym_array_repeat1 = 57,
  aux_sym_string_repeat1 = 58,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_nya] = "nya",
  [anon_sym_object] = "type",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_any] = "type",
  [anon_sym_null] = "null",
  [anon_sym_COMMA] = ",",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_escape_sequence] = "escape_sequence",
  [sym_number] = "number",
  [anon_sym_void] = "void",
  [anon_sym_b8] = "b8",
  [anon_sym_b16] = "b16",
  [anon_sym_b32] = "b32",
  [anon_sym_b64] = "b64",
  [anon_sym_b128] = "b128",
  [anon_sym_u8] = "u8",
  [anon_sym_u16] = "u16",
  [anon_sym_u32] = "u32",
  [anon_sym_u64] = "u64",
  [anon_sym_u128] = "u128",
  [anon_sym_s8] = "s8",
  [anon_sym_s16] = "s16",
  [anon_sym_s32] = "s32",
  [anon_sym_s64] = "s64",
  [anon_sym_s128] = "s128",
  [anon_sym_f16] = "f16",
  [anon_sym_f32] = "f32",
  [anon_sym_f64] = "f64",
  [anon_sym_f128] = "f128",
  [anon_sym_char] = "char",
  [anon_sym_wchar] = "wchar",
  [anon_sym_string] = "string",
  [anon_sym_wstring] = "wstring",
  [anon_sym_array] = "array",
  [sym_comment] = "comment",
  [sym_document] = "document",
  [sym_header] = "header",
  [sym_object] = "object",
  [sym_member] = "member",
  [sym__value] = "_value",
  [sym_scalar] = "scalar",
  [sym_array] = "array",
  [sym_boolean] = "boolean",
  [sym_null] = "null",
  [sym_string] = "string",
  [sym_type] = "type",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_nya] = anon_sym_nya,
  [anon_sym_object] = sym_type,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_any] = sym_type,
  [anon_sym_null] = anon_sym_null,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_number] = sym_number,
  [anon_sym_void] = anon_sym_void,
  [anon_sym_b8] = anon_sym_b8,
  [anon_sym_b16] = anon_sym_b16,
  [anon_sym_b32] = anon_sym_b32,
  [anon_sym_b64] = anon_sym_b64,
  [anon_sym_b128] = anon_sym_b128,
  [anon_sym_u8] = anon_sym_u8,
  [anon_sym_u16] = anon_sym_u16,
  [anon_sym_u32] = anon_sym_u32,
  [anon_sym_u64] = anon_sym_u64,
  [anon_sym_u128] = anon_sym_u128,
  [anon_sym_s8] = anon_sym_s8,
  [anon_sym_s16] = anon_sym_s16,
  [anon_sym_s32] = anon_sym_s32,
  [anon_sym_s64] = anon_sym_s64,
  [anon_sym_s128] = anon_sym_s128,
  [anon_sym_f16] = anon_sym_f16,
  [anon_sym_f32] = anon_sym_f32,
  [anon_sym_f64] = anon_sym_f64,
  [anon_sym_f128] = anon_sym_f128,
  [anon_sym_char] = anon_sym_char,
  [anon_sym_wchar] = anon_sym_wchar,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_wstring] = anon_sym_wstring,
  [anon_sym_array] = anon_sym_array,
  [sym_comment] = sym_comment,
  [sym_document] = sym_document,
  [sym_header] = sym_header,
  [sym_object] = sym_object,
  [sym_member] = sym_member,
  [sym__value] = sym__value,
  [sym_scalar] = sym_scalar,
  [sym_array] = sym_array,
  [sym_boolean] = sym_boolean,
  [sym_null] = sym_null,
  [sym_string] = sym_string,
  [sym_type] = sym_type,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_nya] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_object] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_any] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_void] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_b8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_b16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_b32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_b64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_b128] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u128] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_s8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_s16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_s32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_s64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_s128] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f128] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_char] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_wchar] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_wstring] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_array] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_member] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_scalar] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_checksum = 1,
  field_key = 2,
  field_root = 3,
  field_type = 4,
  field_value = 5,
  field_version = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_checksum] = "checksum",
  [field_key] = "key",
  [field_root] = "root",
  [field_type] = "type",
  [field_value] = "value",
  [field_version] = "version",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 3, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_root, 1},
  [1] =
    {field_checksum, 2},
    {field_version, 1},
  [3] =
    {field_type, 0},
  [4] =
    {field_key, 0},
    {field_value, 2},
  [6] =
    {field_type, 0},
    {field_value, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [6] = {
    [0] = sym_type,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 21,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 30,
  [36] = 27,
  [37] = 26,
  [38] = 34,
  [39] = 19,
  [40] = 40,
  [41] = 41,
  [42] = 17,
  [43] = 20,
  [44] = 18,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 47,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '"', 22,
        ',', 21,
        '-', 5,
        '/', 2,
        '0', 30,
        ':', 17,
        ';', 18,
        '[', 19,
        '\\', 12,
        ']', 20,
        '{', 15,
        '}', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(39);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '0') ADVANCE(30);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 6:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 7:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(35);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(32);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(34);
      END_STATE();
    case 12:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '"', 22,
        ',', 21,
        '-', 5,
        '/', 2,
        '0', 30,
        ':', 17,
        ';', 18,
        '[', 19,
        ']', 20,
        '{', 15,
        '}', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(26);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(28);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(25);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(8);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(7);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(6);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(8);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'f', 4,
        'n', 5,
        'o', 6,
        's', 7,
        't', 8,
        'u', 9,
        'v', 10,
        'w', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(12);
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == '1') ADVANCE(14);
      if (lookahead == '3') ADVANCE(15);
      if (lookahead == '6') ADVANCE(16);
      if (lookahead == '8') ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == 'h') ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == '1') ADVANCE(19);
      if (lookahead == '3') ADVANCE(20);
      if (lookahead == '6') ADVANCE(21);
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == 'u') ADVANCE(23);
      if (lookahead == 'y') ADVANCE(24);
      END_STATE();
    case 6:
      if (lookahead == 'b') ADVANCE(25);
      END_STATE();
    case 7:
      if (lookahead == '1') ADVANCE(26);
      if (lookahead == '3') ADVANCE(27);
      if (lookahead == '6') ADVANCE(28);
      if (lookahead == '8') ADVANCE(29);
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 9:
      if (lookahead == '1') ADVANCE(32);
      if (lookahead == '3') ADVANCE(33);
      if (lookahead == '6') ADVANCE(34);
      if (lookahead == '8') ADVANCE(35);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(37);
      if (lookahead == 's') ADVANCE(38);
      END_STATE();
    case 12:
      if (lookahead == 'y') ADVANCE(39);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 14:
      if (lookahead == '2') ADVANCE(41);
      if (lookahead == '6') ADVANCE(42);
      END_STATE();
    case 15:
      if (lookahead == '2') ADVANCE(43);
      END_STATE();
    case 16:
      if (lookahead == '4') ADVANCE(44);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_b8);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(45);
      END_STATE();
    case 19:
      if (lookahead == '2') ADVANCE(46);
      if (lookahead == '6') ADVANCE(47);
      END_STATE();
    case 20:
      if (lookahead == '2') ADVANCE(48);
      END_STATE();
    case 21:
      if (lookahead == '4') ADVANCE(49);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(50);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(51);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(52);
      END_STATE();
    case 25:
      if (lookahead == 'j') ADVANCE(53);
      END_STATE();
    case 26:
      if (lookahead == '2') ADVANCE(54);
      if (lookahead == '6') ADVANCE(55);
      END_STATE();
    case 27:
      if (lookahead == '2') ADVANCE(56);
      END_STATE();
    case 28:
      if (lookahead == '4') ADVANCE(57);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_s8);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(58);
      END_STATE();
    case 31:
      if (lookahead == 'u') ADVANCE(59);
      END_STATE();
    case 32:
      if (lookahead == '2') ADVANCE(60);
      if (lookahead == '6') ADVANCE(61);
      END_STATE();
    case 33:
      if (lookahead == '2') ADVANCE(62);
      END_STATE();
    case 34:
      if (lookahead == '4') ADVANCE(63);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_u8);
      END_STATE();
    case 36:
      if (lookahead == 'i') ADVANCE(64);
      END_STATE();
    case 37:
      if (lookahead == 'h') ADVANCE(65);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(66);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_any);
      END_STATE();
    case 40:
      if (lookahead == 'a') ADVANCE(67);
      END_STATE();
    case 41:
      if (lookahead == '8') ADVANCE(68);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_b16);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_b32);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_b64);
      END_STATE();
    case 45:
      if (lookahead == 'r') ADVANCE(69);
      END_STATE();
    case 46:
      if (lookahead == '8') ADVANCE(70);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_f16);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_f32);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_f64);
      END_STATE();
    case 50:
      if (lookahead == 's') ADVANCE(71);
      END_STATE();
    case 51:
      if (lookahead == 'l') ADVANCE(72);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_nya);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 54:
      if (lookahead == '8') ADVANCE(74);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_s16);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_s32);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_s64);
      END_STATE();
    case 58:
      if (lookahead == 'i') ADVANCE(75);
      END_STATE();
    case 59:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 60:
      if (lookahead == '8') ADVANCE(77);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_u16);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_u32);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_u64);
      END_STATE();
    case 64:
      if (lookahead == 'd') ADVANCE(78);
      END_STATE();
    case 65:
      if (lookahead == 'a') ADVANCE(79);
      END_STATE();
    case 66:
      if (lookahead == 'r') ADVANCE(80);
      END_STATE();
    case 67:
      if (lookahead == 'y') ADVANCE(81);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_b128);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_char);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_f128);
      END_STATE();
    case 71:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_null);
      END_STATE();
    case 73:
      if (lookahead == 'c') ADVANCE(83);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_s128);
      END_STATE();
    case 75:
      if (lookahead == 'n') ADVANCE(84);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_u128);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_void);
      END_STATE();
    case 79:
      if (lookahead == 'r') ADVANCE(85);
      END_STATE();
    case 80:
      if (lookahead == 'i') ADVANCE(86);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_array);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 83:
      if (lookahead == 't') ADVANCE(87);
      END_STATE();
    case 84:
      if (lookahead == 'g') ADVANCE(88);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_wchar);
      END_STATE();
    case 86:
      if (lookahead == 'n') ADVANCE(89);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_object);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 89:
      if (lookahead == 'g') ADVANCE(90);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_wstring);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_nya] = ACTIONS(1),
    [anon_sym_object] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_any] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_void] = ACTIONS(1),
    [anon_sym_b8] = ACTIONS(1),
    [anon_sym_b16] = ACTIONS(1),
    [anon_sym_b32] = ACTIONS(1),
    [anon_sym_b64] = ACTIONS(1),
    [anon_sym_b128] = ACTIONS(1),
    [anon_sym_u8] = ACTIONS(1),
    [anon_sym_u16] = ACTIONS(1),
    [anon_sym_u32] = ACTIONS(1),
    [anon_sym_u64] = ACTIONS(1),
    [anon_sym_u128] = ACTIONS(1),
    [anon_sym_s8] = ACTIONS(1),
    [anon_sym_s16] = ACTIONS(1),
    [anon_sym_s32] = ACTIONS(1),
    [anon_sym_s64] = ACTIONS(1),
    [anon_sym_s128] = ACTIONS(1),
    [anon_sym_f16] = ACTIONS(1),
    [anon_sym_f32] = ACTIONS(1),
    [anon_sym_f64] = ACTIONS(1),
    [anon_sym_f128] = ACTIONS(1),
    [anon_sym_char] = ACTIONS(1),
    [anon_sym_wchar] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_wstring] = ACTIONS(1),
    [anon_sym_array] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_document] = STATE(55),
    [sym_header] = STATE(40),
    [anon_sym_nya] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_object] = STATE(22),
    [sym__value] = STATE(22),
    [sym_scalar] = STATE(22),
    [sym_array] = STATE(22),
    [sym_boolean] = STATE(22),
    [sym_null] = STATE(22),
    [sym_string] = STATE(22),
    [sym_type] = STATE(24),
    [aux_sym_array_repeat1] = STATE(2),
    [anon_sym_object] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(10),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(16),
    [anon_sym_any] = ACTIONS(18),
    [anon_sym_null] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(24),
    [anon_sym_false] = ACTIONS(24),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(30),
    [anon_sym_void] = ACTIONS(33),
    [anon_sym_b8] = ACTIONS(33),
    [anon_sym_b16] = ACTIONS(33),
    [anon_sym_b32] = ACTIONS(33),
    [anon_sym_b64] = ACTIONS(33),
    [anon_sym_b128] = ACTIONS(33),
    [anon_sym_u8] = ACTIONS(33),
    [anon_sym_u16] = ACTIONS(33),
    [anon_sym_u32] = ACTIONS(33),
    [anon_sym_u64] = ACTIONS(33),
    [anon_sym_u128] = ACTIONS(33),
    [anon_sym_s8] = ACTIONS(33),
    [anon_sym_s16] = ACTIONS(33),
    [anon_sym_s32] = ACTIONS(33),
    [anon_sym_s64] = ACTIONS(33),
    [anon_sym_s128] = ACTIONS(33),
    [anon_sym_f16] = ACTIONS(33),
    [anon_sym_f32] = ACTIONS(33),
    [anon_sym_f64] = ACTIONS(33),
    [anon_sym_f128] = ACTIONS(33),
    [anon_sym_char] = ACTIONS(33),
    [anon_sym_wchar] = ACTIONS(33),
    [anon_sym_string] = ACTIONS(33),
    [anon_sym_wstring] = ACTIONS(33),
    [anon_sym_array] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_object] = STATE(22),
    [sym__value] = STATE(22),
    [sym_scalar] = STATE(22),
    [sym_array] = STATE(22),
    [sym_boolean] = STATE(22),
    [sym_null] = STATE(22),
    [sym_string] = STATE(22),
    [sym_type] = STATE(24),
    [aux_sym_array_repeat1] = STATE(2),
    [anon_sym_object] = ACTIONS(36),
    [anon_sym_LBRACE] = ACTIONS(38),
    [anon_sym_LBRACK] = ACTIONS(40),
    [anon_sym_RBRACK] = ACTIONS(42),
    [anon_sym_any] = ACTIONS(44),
    [anon_sym_null] = ACTIONS(46),
    [anon_sym_true] = ACTIONS(48),
    [anon_sym_false] = ACTIONS(48),
    [anon_sym_DQUOTE] = ACTIONS(50),
    [sym_number] = ACTIONS(52),
    [anon_sym_void] = ACTIONS(54),
    [anon_sym_b8] = ACTIONS(54),
    [anon_sym_b16] = ACTIONS(54),
    [anon_sym_b32] = ACTIONS(54),
    [anon_sym_b64] = ACTIONS(54),
    [anon_sym_b128] = ACTIONS(54),
    [anon_sym_u8] = ACTIONS(54),
    [anon_sym_u16] = ACTIONS(54),
    [anon_sym_u32] = ACTIONS(54),
    [anon_sym_u64] = ACTIONS(54),
    [anon_sym_u128] = ACTIONS(54),
    [anon_sym_s8] = ACTIONS(54),
    [anon_sym_s16] = ACTIONS(54),
    [anon_sym_s32] = ACTIONS(54),
    [anon_sym_s64] = ACTIONS(54),
    [anon_sym_s128] = ACTIONS(54),
    [anon_sym_f16] = ACTIONS(54),
    [anon_sym_f32] = ACTIONS(54),
    [anon_sym_f64] = ACTIONS(54),
    [anon_sym_f128] = ACTIONS(54),
    [anon_sym_char] = ACTIONS(54),
    [anon_sym_wchar] = ACTIONS(54),
    [anon_sym_string] = ACTIONS(54),
    [anon_sym_wstring] = ACTIONS(54),
    [anon_sym_array] = ACTIONS(54),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym_object] = STATE(22),
    [sym__value] = STATE(22),
    [sym_scalar] = STATE(22),
    [sym_array] = STATE(22),
    [sym_boolean] = STATE(22),
    [sym_null] = STATE(22),
    [sym_string] = STATE(22),
    [sym_type] = STATE(24),
    [aux_sym_array_repeat1] = STATE(6),
    [anon_sym_object] = ACTIONS(36),
    [anon_sym_LBRACE] = ACTIONS(38),
    [anon_sym_LBRACK] = ACTIONS(40),
    [anon_sym_RBRACK] = ACTIONS(56),
    [anon_sym_any] = ACTIONS(44),
    [anon_sym_null] = ACTIONS(46),
    [anon_sym_true] = ACTIONS(48),
    [anon_sym_false] = ACTIONS(48),
    [anon_sym_DQUOTE] = ACTIONS(50),
    [sym_number] = ACTIONS(52),
    [anon_sym_void] = ACTIONS(54),
    [anon_sym_b8] = ACTIONS(54),
    [anon_sym_b16] = ACTIONS(54),
    [anon_sym_b32] = ACTIONS(54),
    [anon_sym_b64] = ACTIONS(54),
    [anon_sym_b128] = ACTIONS(54),
    [anon_sym_u8] = ACTIONS(54),
    [anon_sym_u16] = ACTIONS(54),
    [anon_sym_u32] = ACTIONS(54),
    [anon_sym_u64] = ACTIONS(54),
    [anon_sym_u128] = ACTIONS(54),
    [anon_sym_s8] = ACTIONS(54),
    [anon_sym_s16] = ACTIONS(54),
    [anon_sym_s32] = ACTIONS(54),
    [anon_sym_s64] = ACTIONS(54),
    [anon_sym_s128] = ACTIONS(54),
    [anon_sym_f16] = ACTIONS(54),
    [anon_sym_f32] = ACTIONS(54),
    [anon_sym_f64] = ACTIONS(54),
    [anon_sym_f128] = ACTIONS(54),
    [anon_sym_char] = ACTIONS(54),
    [anon_sym_wchar] = ACTIONS(54),
    [anon_sym_string] = ACTIONS(54),
    [anon_sym_wstring] = ACTIONS(54),
    [anon_sym_array] = ACTIONS(54),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym_object] = STATE(22),
    [sym__value] = STATE(22),
    [sym_scalar] = STATE(22),
    [sym_array] = STATE(22),
    [sym_boolean] = STATE(22),
    [sym_null] = STATE(22),
    [sym_string] = STATE(22),
    [sym_type] = STATE(24),
    [aux_sym_array_repeat1] = STATE(3),
    [anon_sym_object] = ACTIONS(36),
    [anon_sym_LBRACE] = ACTIONS(38),
    [anon_sym_LBRACK] = ACTIONS(40),
    [anon_sym_RBRACK] = ACTIONS(58),
    [anon_sym_any] = ACTIONS(44),
    [anon_sym_null] = ACTIONS(46),
    [anon_sym_true] = ACTIONS(48),
    [anon_sym_false] = ACTIONS(48),
    [anon_sym_DQUOTE] = ACTIONS(50),
    [sym_number] = ACTIONS(52),
    [anon_sym_void] = ACTIONS(54),
    [anon_sym_b8] = ACTIONS(54),
    [anon_sym_b16] = ACTIONS(54),
    [anon_sym_b32] = ACTIONS(54),
    [anon_sym_b64] = ACTIONS(54),
    [anon_sym_b128] = ACTIONS(54),
    [anon_sym_u8] = ACTIONS(54),
    [anon_sym_u16] = ACTIONS(54),
    [anon_sym_u32] = ACTIONS(54),
    [anon_sym_u64] = ACTIONS(54),
    [anon_sym_u128] = ACTIONS(54),
    [anon_sym_s8] = ACTIONS(54),
    [anon_sym_s16] = ACTIONS(54),
    [anon_sym_s32] = ACTIONS(54),
    [anon_sym_s64] = ACTIONS(54),
    [anon_sym_s128] = ACTIONS(54),
    [anon_sym_f16] = ACTIONS(54),
    [anon_sym_f32] = ACTIONS(54),
    [anon_sym_f64] = ACTIONS(54),
    [anon_sym_f128] = ACTIONS(54),
    [anon_sym_char] = ACTIONS(54),
    [anon_sym_wchar] = ACTIONS(54),
    [anon_sym_string] = ACTIONS(54),
    [anon_sym_wstring] = ACTIONS(54),
    [anon_sym_array] = ACTIONS(54),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym_object] = STATE(22),
    [sym__value] = STATE(22),
    [sym_scalar] = STATE(22),
    [sym_array] = STATE(22),
    [sym_boolean] = STATE(22),
    [sym_null] = STATE(22),
    [sym_string] = STATE(22),
    [sym_type] = STATE(24),
    [aux_sym_array_repeat1] = STATE(2),
    [anon_sym_object] = ACTIONS(36),
    [anon_sym_LBRACE] = ACTIONS(38),
    [anon_sym_LBRACK] = ACTIONS(40),
    [anon_sym_RBRACK] = ACTIONS(60),
    [anon_sym_any] = ACTIONS(44),
    [anon_sym_null] = ACTIONS(46),
    [anon_sym_true] = ACTIONS(48),
    [anon_sym_false] = ACTIONS(48),
    [anon_sym_DQUOTE] = ACTIONS(50),
    [sym_number] = ACTIONS(52),
    [anon_sym_void] = ACTIONS(54),
    [anon_sym_b8] = ACTIONS(54),
    [anon_sym_b16] = ACTIONS(54),
    [anon_sym_b32] = ACTIONS(54),
    [anon_sym_b64] = ACTIONS(54),
    [anon_sym_b128] = ACTIONS(54),
    [anon_sym_u8] = ACTIONS(54),
    [anon_sym_u16] = ACTIONS(54),
    [anon_sym_u32] = ACTIONS(54),
    [anon_sym_u64] = ACTIONS(54),
    [anon_sym_u128] = ACTIONS(54),
    [anon_sym_s8] = ACTIONS(54),
    [anon_sym_s16] = ACTIONS(54),
    [anon_sym_s32] = ACTIONS(54),
    [anon_sym_s64] = ACTIONS(54),
    [anon_sym_s128] = ACTIONS(54),
    [anon_sym_f16] = ACTIONS(54),
    [anon_sym_f32] = ACTIONS(54),
    [anon_sym_f64] = ACTIONS(54),
    [anon_sym_f128] = ACTIONS(54),
    [anon_sym_char] = ACTIONS(54),
    [anon_sym_wchar] = ACTIONS(54),
    [anon_sym_string] = ACTIONS(54),
    [anon_sym_wstring] = ACTIONS(54),
    [anon_sym_array] = ACTIONS(54),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym_object] = STATE(41),
    [sym__value] = STATE(41),
    [sym_scalar] = STATE(41),
    [sym_array] = STATE(41),
    [sym_boolean] = STATE(41),
    [sym_null] = STATE(41),
    [sym_string] = STATE(41),
    [sym_type] = STATE(24),
    [anon_sym_object] = ACTIONS(62),
    [anon_sym_LBRACE] = ACTIONS(64),
    [anon_sym_LBRACK] = ACTIONS(40),
    [anon_sym_any] = ACTIONS(44),
    [anon_sym_null] = ACTIONS(66),
    [anon_sym_true] = ACTIONS(48),
    [anon_sym_false] = ACTIONS(48),
    [anon_sym_DQUOTE] = ACTIONS(50),
    [sym_number] = ACTIONS(68),
    [anon_sym_void] = ACTIONS(54),
    [anon_sym_b8] = ACTIONS(54),
    [anon_sym_b16] = ACTIONS(54),
    [anon_sym_b32] = ACTIONS(54),
    [anon_sym_b64] = ACTIONS(54),
    [anon_sym_b128] = ACTIONS(54),
    [anon_sym_u8] = ACTIONS(54),
    [anon_sym_u16] = ACTIONS(54),
    [anon_sym_u32] = ACTIONS(54),
    [anon_sym_u64] = ACTIONS(54),
    [anon_sym_u128] = ACTIONS(54),
    [anon_sym_s8] = ACTIONS(54),
    [anon_sym_s16] = ACTIONS(54),
    [anon_sym_s32] = ACTIONS(54),
    [anon_sym_s64] = ACTIONS(54),
    [anon_sym_s128] = ACTIONS(54),
    [anon_sym_f16] = ACTIONS(54),
    [anon_sym_f32] = ACTIONS(54),
    [anon_sym_f64] = ACTIONS(54),
    [anon_sym_f128] = ACTIONS(54),
    [anon_sym_char] = ACTIONS(54),
    [anon_sym_wchar] = ACTIONS(54),
    [anon_sym_string] = ACTIONS(54),
    [anon_sym_wstring] = ACTIONS(54),
    [anon_sym_array] = ACTIONS(54),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [sym_identifier] = ACTIONS(70),
    [anon_sym_object] = ACTIONS(70),
    [anon_sym_LBRACE] = ACTIONS(72),
    [anon_sym_RBRACE] = ACTIONS(72),
    [anon_sym_SEMI] = ACTIONS(72),
    [anon_sym_LBRACK] = ACTIONS(72),
    [anon_sym_RBRACK] = ACTIONS(72),
    [anon_sym_any] = ACTIONS(70),
    [anon_sym_null] = ACTIONS(70),
    [anon_sym_COMMA] = ACTIONS(72),
    [anon_sym_true] = ACTIONS(70),
    [anon_sym_false] = ACTIONS(70),
    [anon_sym_DQUOTE] = ACTIONS(72),
    [sym_number] = ACTIONS(72),
    [anon_sym_void] = ACTIONS(70),
    [anon_sym_b8] = ACTIONS(70),
    [anon_sym_b16] = ACTIONS(70),
    [anon_sym_b32] = ACTIONS(70),
    [anon_sym_b64] = ACTIONS(70),
    [anon_sym_b128] = ACTIONS(70),
    [anon_sym_u8] = ACTIONS(70),
    [anon_sym_u16] = ACTIONS(70),
    [anon_sym_u32] = ACTIONS(70),
    [anon_sym_u64] = ACTIONS(70),
    [anon_sym_u128] = ACTIONS(70),
    [anon_sym_s8] = ACTIONS(70),
    [anon_sym_s16] = ACTIONS(70),
    [anon_sym_s32] = ACTIONS(70),
    [anon_sym_s64] = ACTIONS(70),
    [anon_sym_s128] = ACTIONS(70),
    [anon_sym_f16] = ACTIONS(70),
    [anon_sym_f32] = ACTIONS(70),
    [anon_sym_f64] = ACTIONS(70),
    [anon_sym_f128] = ACTIONS(70),
    [anon_sym_char] = ACTIONS(70),
    [anon_sym_wchar] = ACTIONS(70),
    [anon_sym_string] = ACTIONS(70),
    [anon_sym_wstring] = ACTIONS(70),
    [anon_sym_array] = ACTIONS(70),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [sym_identifier] = ACTIONS(74),
    [anon_sym_object] = ACTIONS(74),
    [anon_sym_LBRACE] = ACTIONS(76),
    [anon_sym_RBRACE] = ACTIONS(76),
    [anon_sym_SEMI] = ACTIONS(76),
    [anon_sym_LBRACK] = ACTIONS(76),
    [anon_sym_RBRACK] = ACTIONS(76),
    [anon_sym_any] = ACTIONS(74),
    [anon_sym_null] = ACTIONS(74),
    [anon_sym_COMMA] = ACTIONS(76),
    [anon_sym_true] = ACTIONS(74),
    [anon_sym_false] = ACTIONS(74),
    [anon_sym_DQUOTE] = ACTIONS(76),
    [sym_number] = ACTIONS(76),
    [anon_sym_void] = ACTIONS(74),
    [anon_sym_b8] = ACTIONS(74),
    [anon_sym_b16] = ACTIONS(74),
    [anon_sym_b32] = ACTIONS(74),
    [anon_sym_b64] = ACTIONS(74),
    [anon_sym_b128] = ACTIONS(74),
    [anon_sym_u8] = ACTIONS(74),
    [anon_sym_u16] = ACTIONS(74),
    [anon_sym_u32] = ACTIONS(74),
    [anon_sym_u64] = ACTIONS(74),
    [anon_sym_u128] = ACTIONS(74),
    [anon_sym_s8] = ACTIONS(74),
    [anon_sym_s16] = ACTIONS(74),
    [anon_sym_s32] = ACTIONS(74),
    [anon_sym_s64] = ACTIONS(74),
    [anon_sym_s128] = ACTIONS(74),
    [anon_sym_f16] = ACTIONS(74),
    [anon_sym_f32] = ACTIONS(74),
    [anon_sym_f64] = ACTIONS(74),
    [anon_sym_f128] = ACTIONS(74),
    [anon_sym_char] = ACTIONS(74),
    [anon_sym_wchar] = ACTIONS(74),
    [anon_sym_string] = ACTIONS(74),
    [anon_sym_wstring] = ACTIONS(74),
    [anon_sym_array] = ACTIONS(74),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [sym_identifier] = ACTIONS(78),
    [anon_sym_object] = ACTIONS(78),
    [anon_sym_LBRACE] = ACTIONS(80),
    [anon_sym_RBRACE] = ACTIONS(80),
    [anon_sym_SEMI] = ACTIONS(80),
    [anon_sym_LBRACK] = ACTIONS(80),
    [anon_sym_RBRACK] = ACTIONS(80),
    [anon_sym_any] = ACTIONS(78),
    [anon_sym_null] = ACTIONS(78),
    [anon_sym_COMMA] = ACTIONS(80),
    [anon_sym_true] = ACTIONS(78),
    [anon_sym_false] = ACTIONS(78),
    [anon_sym_DQUOTE] = ACTIONS(80),
    [sym_number] = ACTIONS(80),
    [anon_sym_void] = ACTIONS(78),
    [anon_sym_b8] = ACTIONS(78),
    [anon_sym_b16] = ACTIONS(78),
    [anon_sym_b32] = ACTIONS(78),
    [anon_sym_b64] = ACTIONS(78),
    [anon_sym_b128] = ACTIONS(78),
    [anon_sym_u8] = ACTIONS(78),
    [anon_sym_u16] = ACTIONS(78),
    [anon_sym_u32] = ACTIONS(78),
    [anon_sym_u64] = ACTIONS(78),
    [anon_sym_u128] = ACTIONS(78),
    [anon_sym_s8] = ACTIONS(78),
    [anon_sym_s16] = ACTIONS(78),
    [anon_sym_s32] = ACTIONS(78),
    [anon_sym_s64] = ACTIONS(78),
    [anon_sym_s128] = ACTIONS(78),
    [anon_sym_f16] = ACTIONS(78),
    [anon_sym_f32] = ACTIONS(78),
    [anon_sym_f64] = ACTIONS(78),
    [anon_sym_f128] = ACTIONS(78),
    [anon_sym_char] = ACTIONS(78),
    [anon_sym_wchar] = ACTIONS(78),
    [anon_sym_string] = ACTIONS(78),
    [anon_sym_wstring] = ACTIONS(78),
    [anon_sym_array] = ACTIONS(78),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(11)] = {
    [sym_identifier] = ACTIONS(82),
    [anon_sym_object] = ACTIONS(82),
    [anon_sym_LBRACE] = ACTIONS(84),
    [anon_sym_RBRACE] = ACTIONS(84),
    [anon_sym_SEMI] = ACTIONS(84),
    [anon_sym_LBRACK] = ACTIONS(84),
    [anon_sym_RBRACK] = ACTIONS(84),
    [anon_sym_any] = ACTIONS(82),
    [anon_sym_null] = ACTIONS(82),
    [anon_sym_COMMA] = ACTIONS(84),
    [anon_sym_true] = ACTIONS(82),
    [anon_sym_false] = ACTIONS(82),
    [anon_sym_DQUOTE] = ACTIONS(84),
    [sym_number] = ACTIONS(84),
    [anon_sym_void] = ACTIONS(82),
    [anon_sym_b8] = ACTIONS(82),
    [anon_sym_b16] = ACTIONS(82),
    [anon_sym_b32] = ACTIONS(82),
    [anon_sym_b64] = ACTIONS(82),
    [anon_sym_b128] = ACTIONS(82),
    [anon_sym_u8] = ACTIONS(82),
    [anon_sym_u16] = ACTIONS(82),
    [anon_sym_u32] = ACTIONS(82),
    [anon_sym_u64] = ACTIONS(82),
    [anon_sym_u128] = ACTIONS(82),
    [anon_sym_s8] = ACTIONS(82),
    [anon_sym_s16] = ACTIONS(82),
    [anon_sym_s32] = ACTIONS(82),
    [anon_sym_s64] = ACTIONS(82),
    [anon_sym_s128] = ACTIONS(82),
    [anon_sym_f16] = ACTIONS(82),
    [anon_sym_f32] = ACTIONS(82),
    [anon_sym_f64] = ACTIONS(82),
    [anon_sym_f128] = ACTIONS(82),
    [anon_sym_char] = ACTIONS(82),
    [anon_sym_wchar] = ACTIONS(82),
    [anon_sym_string] = ACTIONS(82),
    [anon_sym_wstring] = ACTIONS(82),
    [anon_sym_array] = ACTIONS(82),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(12)] = {
    [sym_identifier] = ACTIONS(86),
    [anon_sym_object] = ACTIONS(86),
    [anon_sym_LBRACE] = ACTIONS(88),
    [anon_sym_RBRACE] = ACTIONS(88),
    [anon_sym_SEMI] = ACTIONS(88),
    [anon_sym_LBRACK] = ACTIONS(88),
    [anon_sym_RBRACK] = ACTIONS(88),
    [anon_sym_any] = ACTIONS(86),
    [anon_sym_null] = ACTIONS(86),
    [anon_sym_COMMA] = ACTIONS(88),
    [anon_sym_true] = ACTIONS(86),
    [anon_sym_false] = ACTIONS(86),
    [anon_sym_DQUOTE] = ACTIONS(88),
    [sym_number] = ACTIONS(88),
    [anon_sym_void] = ACTIONS(86),
    [anon_sym_b8] = ACTIONS(86),
    [anon_sym_b16] = ACTIONS(86),
    [anon_sym_b32] = ACTIONS(86),
    [anon_sym_b64] = ACTIONS(86),
    [anon_sym_b128] = ACTIONS(86),
    [anon_sym_u8] = ACTIONS(86),
    [anon_sym_u16] = ACTIONS(86),
    [anon_sym_u32] = ACTIONS(86),
    [anon_sym_u64] = ACTIONS(86),
    [anon_sym_u128] = ACTIONS(86),
    [anon_sym_s8] = ACTIONS(86),
    [anon_sym_s16] = ACTIONS(86),
    [anon_sym_s32] = ACTIONS(86),
    [anon_sym_s64] = ACTIONS(86),
    [anon_sym_s128] = ACTIONS(86),
    [anon_sym_f16] = ACTIONS(86),
    [anon_sym_f32] = ACTIONS(86),
    [anon_sym_f64] = ACTIONS(86),
    [anon_sym_f128] = ACTIONS(86),
    [anon_sym_char] = ACTIONS(86),
    [anon_sym_wchar] = ACTIONS(86),
    [anon_sym_string] = ACTIONS(86),
    [anon_sym_wstring] = ACTIONS(86),
    [anon_sym_array] = ACTIONS(86),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(13)] = {
    [sym_identifier] = ACTIONS(90),
    [anon_sym_object] = ACTIONS(90),
    [anon_sym_LBRACE] = ACTIONS(92),
    [anon_sym_RBRACE] = ACTIONS(92),
    [anon_sym_SEMI] = ACTIONS(92),
    [anon_sym_LBRACK] = ACTIONS(92),
    [anon_sym_RBRACK] = ACTIONS(92),
    [anon_sym_any] = ACTIONS(90),
    [anon_sym_null] = ACTIONS(90),
    [anon_sym_COMMA] = ACTIONS(92),
    [anon_sym_true] = ACTIONS(90),
    [anon_sym_false] = ACTIONS(90),
    [anon_sym_DQUOTE] = ACTIONS(92),
    [sym_number] = ACTIONS(92),
    [anon_sym_void] = ACTIONS(90),
    [anon_sym_b8] = ACTIONS(90),
    [anon_sym_b16] = ACTIONS(90),
    [anon_sym_b32] = ACTIONS(90),
    [anon_sym_b64] = ACTIONS(90),
    [anon_sym_b128] = ACTIONS(90),
    [anon_sym_u8] = ACTIONS(90),
    [anon_sym_u16] = ACTIONS(90),
    [anon_sym_u32] = ACTIONS(90),
    [anon_sym_u64] = ACTIONS(90),
    [anon_sym_u128] = ACTIONS(90),
    [anon_sym_s8] = ACTIONS(90),
    [anon_sym_s16] = ACTIONS(90),
    [anon_sym_s32] = ACTIONS(90),
    [anon_sym_s64] = ACTIONS(90),
    [anon_sym_s128] = ACTIONS(90),
    [anon_sym_f16] = ACTIONS(90),
    [anon_sym_f32] = ACTIONS(90),
    [anon_sym_f64] = ACTIONS(90),
    [anon_sym_f128] = ACTIONS(90),
    [anon_sym_char] = ACTIONS(90),
    [anon_sym_wchar] = ACTIONS(90),
    [anon_sym_string] = ACTIONS(90),
    [anon_sym_wstring] = ACTIONS(90),
    [anon_sym_array] = ACTIONS(90),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(14)] = {
    [sym_identifier] = ACTIONS(94),
    [anon_sym_object] = ACTIONS(94),
    [anon_sym_LBRACE] = ACTIONS(96),
    [anon_sym_RBRACE] = ACTIONS(96),
    [anon_sym_SEMI] = ACTIONS(96),
    [anon_sym_LBRACK] = ACTIONS(96),
    [anon_sym_RBRACK] = ACTIONS(96),
    [anon_sym_any] = ACTIONS(94),
    [anon_sym_null] = ACTIONS(94),
    [anon_sym_COMMA] = ACTIONS(96),
    [anon_sym_true] = ACTIONS(94),
    [anon_sym_false] = ACTIONS(94),
    [anon_sym_DQUOTE] = ACTIONS(96),
    [sym_number] = ACTIONS(96),
    [anon_sym_void] = ACTIONS(94),
    [anon_sym_b8] = ACTIONS(94),
    [anon_sym_b16] = ACTIONS(94),
    [anon_sym_b32] = ACTIONS(94),
    [anon_sym_b64] = ACTIONS(94),
    [anon_sym_b128] = ACTIONS(94),
    [anon_sym_u8] = ACTIONS(94),
    [anon_sym_u16] = ACTIONS(94),
    [anon_sym_u32] = ACTIONS(94),
    [anon_sym_u64] = ACTIONS(94),
    [anon_sym_u128] = ACTIONS(94),
    [anon_sym_s8] = ACTIONS(94),
    [anon_sym_s16] = ACTIONS(94),
    [anon_sym_s32] = ACTIONS(94),
    [anon_sym_s64] = ACTIONS(94),
    [anon_sym_s128] = ACTIONS(94),
    [anon_sym_f16] = ACTIONS(94),
    [anon_sym_f32] = ACTIONS(94),
    [anon_sym_f64] = ACTIONS(94),
    [anon_sym_f128] = ACTIONS(94),
    [anon_sym_char] = ACTIONS(94),
    [anon_sym_wchar] = ACTIONS(94),
    [anon_sym_string] = ACTIONS(94),
    [anon_sym_wstring] = ACTIONS(94),
    [anon_sym_array] = ACTIONS(94),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(15)] = {
    [sym_identifier] = ACTIONS(98),
    [anon_sym_object] = ACTIONS(98),
    [anon_sym_LBRACE] = ACTIONS(100),
    [anon_sym_RBRACE] = ACTIONS(100),
    [anon_sym_SEMI] = ACTIONS(100),
    [anon_sym_LBRACK] = ACTIONS(100),
    [anon_sym_RBRACK] = ACTIONS(100),
    [anon_sym_any] = ACTIONS(98),
    [anon_sym_null] = ACTIONS(98),
    [anon_sym_COMMA] = ACTIONS(100),
    [anon_sym_true] = ACTIONS(98),
    [anon_sym_false] = ACTIONS(98),
    [anon_sym_DQUOTE] = ACTIONS(100),
    [sym_number] = ACTIONS(100),
    [anon_sym_void] = ACTIONS(98),
    [anon_sym_b8] = ACTIONS(98),
    [anon_sym_b16] = ACTIONS(98),
    [anon_sym_b32] = ACTIONS(98),
    [anon_sym_b64] = ACTIONS(98),
    [anon_sym_b128] = ACTIONS(98),
    [anon_sym_u8] = ACTIONS(98),
    [anon_sym_u16] = ACTIONS(98),
    [anon_sym_u32] = ACTIONS(98),
    [anon_sym_u64] = ACTIONS(98),
    [anon_sym_u128] = ACTIONS(98),
    [anon_sym_s8] = ACTIONS(98),
    [anon_sym_s16] = ACTIONS(98),
    [anon_sym_s32] = ACTIONS(98),
    [anon_sym_s64] = ACTIONS(98),
    [anon_sym_s128] = ACTIONS(98),
    [anon_sym_f16] = ACTIONS(98),
    [anon_sym_f32] = ACTIONS(98),
    [anon_sym_f64] = ACTIONS(98),
    [anon_sym_f128] = ACTIONS(98),
    [anon_sym_char] = ACTIONS(98),
    [anon_sym_wchar] = ACTIONS(98),
    [anon_sym_string] = ACTIONS(98),
    [anon_sym_wstring] = ACTIONS(98),
    [anon_sym_array] = ACTIONS(98),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(16)] = {
    [sym_identifier] = ACTIONS(102),
    [anon_sym_object] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(104),
    [anon_sym_RBRACE] = ACTIONS(104),
    [anon_sym_SEMI] = ACTIONS(104),
    [anon_sym_LBRACK] = ACTIONS(104),
    [anon_sym_RBRACK] = ACTIONS(104),
    [anon_sym_any] = ACTIONS(102),
    [anon_sym_null] = ACTIONS(102),
    [anon_sym_COMMA] = ACTIONS(104),
    [anon_sym_true] = ACTIONS(102),
    [anon_sym_false] = ACTIONS(102),
    [anon_sym_DQUOTE] = ACTIONS(104),
    [sym_number] = ACTIONS(104),
    [anon_sym_void] = ACTIONS(102),
    [anon_sym_b8] = ACTIONS(102),
    [anon_sym_b16] = ACTIONS(102),
    [anon_sym_b32] = ACTIONS(102),
    [anon_sym_b64] = ACTIONS(102),
    [anon_sym_b128] = ACTIONS(102),
    [anon_sym_u8] = ACTIONS(102),
    [anon_sym_u16] = ACTIONS(102),
    [anon_sym_u32] = ACTIONS(102),
    [anon_sym_u64] = ACTIONS(102),
    [anon_sym_u128] = ACTIONS(102),
    [anon_sym_s8] = ACTIONS(102),
    [anon_sym_s16] = ACTIONS(102),
    [anon_sym_s32] = ACTIONS(102),
    [anon_sym_s64] = ACTIONS(102),
    [anon_sym_s128] = ACTIONS(102),
    [anon_sym_f16] = ACTIONS(102),
    [anon_sym_f32] = ACTIONS(102),
    [anon_sym_f64] = ACTIONS(102),
    [anon_sym_f128] = ACTIONS(102),
    [anon_sym_char] = ACTIONS(102),
    [anon_sym_wchar] = ACTIONS(102),
    [anon_sym_string] = ACTIONS(102),
    [anon_sym_wstring] = ACTIONS(102),
    [anon_sym_array] = ACTIONS(102),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(17)] = {
    [ts_builtin_sym_end] = ACTIONS(106),
    [anon_sym_object] = ACTIONS(106),
    [anon_sym_LBRACE] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_RBRACK] = ACTIONS(106),
    [anon_sym_any] = ACTIONS(106),
    [anon_sym_null] = ACTIONS(106),
    [anon_sym_COMMA] = ACTIONS(106),
    [anon_sym_true] = ACTIONS(106),
    [anon_sym_false] = ACTIONS(106),
    [anon_sym_DQUOTE] = ACTIONS(106),
    [sym_number] = ACTIONS(106),
    [anon_sym_void] = ACTIONS(106),
    [anon_sym_b8] = ACTIONS(106),
    [anon_sym_b16] = ACTIONS(106),
    [anon_sym_b32] = ACTIONS(106),
    [anon_sym_b64] = ACTIONS(106),
    [anon_sym_b128] = ACTIONS(106),
    [anon_sym_u8] = ACTIONS(106),
    [anon_sym_u16] = ACTIONS(106),
    [anon_sym_u32] = ACTIONS(106),
    [anon_sym_u64] = ACTIONS(106),
    [anon_sym_u128] = ACTIONS(106),
    [anon_sym_s8] = ACTIONS(106),
    [anon_sym_s16] = ACTIONS(106),
    [anon_sym_s32] = ACTIONS(106),
    [anon_sym_s64] = ACTIONS(106),
    [anon_sym_s128] = ACTIONS(106),
    [anon_sym_f16] = ACTIONS(106),
    [anon_sym_f32] = ACTIONS(106),
    [anon_sym_f64] = ACTIONS(106),
    [anon_sym_f128] = ACTIONS(106),
    [anon_sym_char] = ACTIONS(106),
    [anon_sym_wchar] = ACTIONS(106),
    [anon_sym_string] = ACTIONS(106),
    [anon_sym_wstring] = ACTIONS(106),
    [anon_sym_array] = ACTIONS(106),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(18)] = {
    [ts_builtin_sym_end] = ACTIONS(108),
    [anon_sym_object] = ACTIONS(108),
    [anon_sym_LBRACE] = ACTIONS(108),
    [anon_sym_LBRACK] = ACTIONS(108),
    [anon_sym_RBRACK] = ACTIONS(108),
    [anon_sym_any] = ACTIONS(108),
    [anon_sym_null] = ACTIONS(108),
    [anon_sym_COMMA] = ACTIONS(108),
    [anon_sym_true] = ACTIONS(108),
    [anon_sym_false] = ACTIONS(108),
    [anon_sym_DQUOTE] = ACTIONS(108),
    [sym_number] = ACTIONS(108),
    [anon_sym_void] = ACTIONS(108),
    [anon_sym_b8] = ACTIONS(108),
    [anon_sym_b16] = ACTIONS(108),
    [anon_sym_b32] = ACTIONS(108),
    [anon_sym_b64] = ACTIONS(108),
    [anon_sym_b128] = ACTIONS(108),
    [anon_sym_u8] = ACTIONS(108),
    [anon_sym_u16] = ACTIONS(108),
    [anon_sym_u32] = ACTIONS(108),
    [anon_sym_u64] = ACTIONS(108),
    [anon_sym_u128] = ACTIONS(108),
    [anon_sym_s8] = ACTIONS(108),
    [anon_sym_s16] = ACTIONS(108),
    [anon_sym_s32] = ACTIONS(108),
    [anon_sym_s64] = ACTIONS(108),
    [anon_sym_s128] = ACTIONS(108),
    [anon_sym_f16] = ACTIONS(108),
    [anon_sym_f32] = ACTIONS(108),
    [anon_sym_f64] = ACTIONS(108),
    [anon_sym_f128] = ACTIONS(108),
    [anon_sym_char] = ACTIONS(108),
    [anon_sym_wchar] = ACTIONS(108),
    [anon_sym_string] = ACTIONS(108),
    [anon_sym_wstring] = ACTIONS(108),
    [anon_sym_array] = ACTIONS(108),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(19)] = {
    [ts_builtin_sym_end] = ACTIONS(110),
    [anon_sym_object] = ACTIONS(110),
    [anon_sym_LBRACE] = ACTIONS(110),
    [anon_sym_LBRACK] = ACTIONS(110),
    [anon_sym_RBRACK] = ACTIONS(110),
    [anon_sym_any] = ACTIONS(110),
    [anon_sym_null] = ACTIONS(110),
    [anon_sym_COMMA] = ACTIONS(110),
    [anon_sym_true] = ACTIONS(110),
    [anon_sym_false] = ACTIONS(110),
    [anon_sym_DQUOTE] = ACTIONS(110),
    [sym_number] = ACTIONS(110),
    [anon_sym_void] = ACTIONS(110),
    [anon_sym_b8] = ACTIONS(110),
    [anon_sym_b16] = ACTIONS(110),
    [anon_sym_b32] = ACTIONS(110),
    [anon_sym_b64] = ACTIONS(110),
    [anon_sym_b128] = ACTIONS(110),
    [anon_sym_u8] = ACTIONS(110),
    [anon_sym_u16] = ACTIONS(110),
    [anon_sym_u32] = ACTIONS(110),
    [anon_sym_u64] = ACTIONS(110),
    [anon_sym_u128] = ACTIONS(110),
    [anon_sym_s8] = ACTIONS(110),
    [anon_sym_s16] = ACTIONS(110),
    [anon_sym_s32] = ACTIONS(110),
    [anon_sym_s64] = ACTIONS(110),
    [anon_sym_s128] = ACTIONS(110),
    [anon_sym_f16] = ACTIONS(110),
    [anon_sym_f32] = ACTIONS(110),
    [anon_sym_f64] = ACTIONS(110),
    [anon_sym_f128] = ACTIONS(110),
    [anon_sym_char] = ACTIONS(110),
    [anon_sym_wchar] = ACTIONS(110),
    [anon_sym_string] = ACTIONS(110),
    [anon_sym_wstring] = ACTIONS(110),
    [anon_sym_array] = ACTIONS(110),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(20)] = {
    [ts_builtin_sym_end] = ACTIONS(112),
    [anon_sym_object] = ACTIONS(112),
    [anon_sym_LBRACE] = ACTIONS(112),
    [anon_sym_LBRACK] = ACTIONS(112),
    [anon_sym_RBRACK] = ACTIONS(112),
    [anon_sym_any] = ACTIONS(112),
    [anon_sym_null] = ACTIONS(112),
    [anon_sym_COMMA] = ACTIONS(112),
    [anon_sym_true] = ACTIONS(112),
    [anon_sym_false] = ACTIONS(112),
    [anon_sym_DQUOTE] = ACTIONS(112),
    [sym_number] = ACTIONS(112),
    [anon_sym_void] = ACTIONS(112),
    [anon_sym_b8] = ACTIONS(112),
    [anon_sym_b16] = ACTIONS(112),
    [anon_sym_b32] = ACTIONS(112),
    [anon_sym_b64] = ACTIONS(112),
    [anon_sym_b128] = ACTIONS(112),
    [anon_sym_u8] = ACTIONS(112),
    [anon_sym_u16] = ACTIONS(112),
    [anon_sym_u32] = ACTIONS(112),
    [anon_sym_u64] = ACTIONS(112),
    [anon_sym_u128] = ACTIONS(112),
    [anon_sym_s8] = ACTIONS(112),
    [anon_sym_s16] = ACTIONS(112),
    [anon_sym_s32] = ACTIONS(112),
    [anon_sym_s64] = ACTIONS(112),
    [anon_sym_s128] = ACTIONS(112),
    [anon_sym_f16] = ACTIONS(112),
    [anon_sym_f32] = ACTIONS(112),
    [anon_sym_f64] = ACTIONS(112),
    [anon_sym_f128] = ACTIONS(112),
    [anon_sym_char] = ACTIONS(112),
    [anon_sym_wchar] = ACTIONS(112),
    [anon_sym_string] = ACTIONS(112),
    [anon_sym_wstring] = ACTIONS(112),
    [anon_sym_array] = ACTIONS(112),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(21)] = {
    [anon_sym_object] = ACTIONS(114),
    [anon_sym_LBRACE] = ACTIONS(114),
    [anon_sym_LBRACK] = ACTIONS(116),
    [anon_sym_RBRACK] = ACTIONS(114),
    [anon_sym_any] = ACTIONS(114),
    [anon_sym_null] = ACTIONS(114),
    [anon_sym_COMMA] = ACTIONS(114),
    [anon_sym_true] = ACTIONS(114),
    [anon_sym_false] = ACTIONS(114),
    [anon_sym_DQUOTE] = ACTIONS(114),
    [sym_number] = ACTIONS(114),
    [anon_sym_void] = ACTIONS(114),
    [anon_sym_b8] = ACTIONS(114),
    [anon_sym_b16] = ACTIONS(114),
    [anon_sym_b32] = ACTIONS(114),
    [anon_sym_b64] = ACTIONS(114),
    [anon_sym_b128] = ACTIONS(114),
    [anon_sym_u8] = ACTIONS(114),
    [anon_sym_u16] = ACTIONS(114),
    [anon_sym_u32] = ACTIONS(114),
    [anon_sym_u64] = ACTIONS(114),
    [anon_sym_u128] = ACTIONS(114),
    [anon_sym_s8] = ACTIONS(114),
    [anon_sym_s16] = ACTIONS(114),
    [anon_sym_s32] = ACTIONS(114),
    [anon_sym_s64] = ACTIONS(114),
    [anon_sym_s128] = ACTIONS(114),
    [anon_sym_f16] = ACTIONS(114),
    [anon_sym_f32] = ACTIONS(114),
    [anon_sym_f64] = ACTIONS(114),
    [anon_sym_f128] = ACTIONS(114),
    [anon_sym_char] = ACTIONS(114),
    [anon_sym_wchar] = ACTIONS(114),
    [anon_sym_string] = ACTIONS(114),
    [anon_sym_wstring] = ACTIONS(114),
    [anon_sym_array] = ACTIONS(114),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(22)] = {
    [anon_sym_object] = ACTIONS(119),
    [anon_sym_LBRACE] = ACTIONS(119),
    [anon_sym_LBRACK] = ACTIONS(119),
    [anon_sym_RBRACK] = ACTIONS(119),
    [anon_sym_any] = ACTIONS(119),
    [anon_sym_null] = ACTIONS(119),
    [anon_sym_COMMA] = ACTIONS(121),
    [anon_sym_true] = ACTIONS(119),
    [anon_sym_false] = ACTIONS(119),
    [anon_sym_DQUOTE] = ACTIONS(119),
    [sym_number] = ACTIONS(119),
    [anon_sym_void] = ACTIONS(119),
    [anon_sym_b8] = ACTIONS(119),
    [anon_sym_b16] = ACTIONS(119),
    [anon_sym_b32] = ACTIONS(119),
    [anon_sym_b64] = ACTIONS(119),
    [anon_sym_b128] = ACTIONS(119),
    [anon_sym_u8] = ACTIONS(119),
    [anon_sym_u16] = ACTIONS(119),
    [anon_sym_u32] = ACTIONS(119),
    [anon_sym_u64] = ACTIONS(119),
    [anon_sym_u128] = ACTIONS(119),
    [anon_sym_s8] = ACTIONS(119),
    [anon_sym_s16] = ACTIONS(119),
    [anon_sym_s32] = ACTIONS(119),
    [anon_sym_s64] = ACTIONS(119),
    [anon_sym_s128] = ACTIONS(119),
    [anon_sym_f16] = ACTIONS(119),
    [anon_sym_f32] = ACTIONS(119),
    [anon_sym_f64] = ACTIONS(119),
    [anon_sym_f128] = ACTIONS(119),
    [anon_sym_char] = ACTIONS(119),
    [anon_sym_wchar] = ACTIONS(119),
    [anon_sym_string] = ACTIONS(119),
    [anon_sym_wstring] = ACTIONS(119),
    [anon_sym_array] = ACTIONS(119),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(23)] = {
    [anon_sym_object] = ACTIONS(16),
    [anon_sym_LBRACE] = ACTIONS(16),
    [anon_sym_LBRACK] = ACTIONS(16),
    [anon_sym_RBRACK] = ACTIONS(16),
    [anon_sym_any] = ACTIONS(16),
    [anon_sym_null] = ACTIONS(16),
    [anon_sym_true] = ACTIONS(16),
    [anon_sym_false] = ACTIONS(16),
    [anon_sym_DQUOTE] = ACTIONS(16),
    [sym_number] = ACTIONS(16),
    [anon_sym_void] = ACTIONS(16),
    [anon_sym_b8] = ACTIONS(16),
    [anon_sym_b16] = ACTIONS(16),
    [anon_sym_b32] = ACTIONS(16),
    [anon_sym_b64] = ACTIONS(16),
    [anon_sym_b128] = ACTIONS(16),
    [anon_sym_u8] = ACTIONS(16),
    [anon_sym_u16] = ACTIONS(16),
    [anon_sym_u32] = ACTIONS(16),
    [anon_sym_u64] = ACTIONS(16),
    [anon_sym_u128] = ACTIONS(16),
    [anon_sym_s8] = ACTIONS(16),
    [anon_sym_s16] = ACTIONS(16),
    [anon_sym_s32] = ACTIONS(16),
    [anon_sym_s64] = ACTIONS(16),
    [anon_sym_s128] = ACTIONS(16),
    [anon_sym_f16] = ACTIONS(16),
    [anon_sym_f32] = ACTIONS(16),
    [anon_sym_f64] = ACTIONS(16),
    [anon_sym_f128] = ACTIONS(16),
    [anon_sym_char] = ACTIONS(16),
    [anon_sym_wchar] = ACTIONS(16),
    [anon_sym_string] = ACTIONS(16),
    [anon_sym_wstring] = ACTIONS(16),
    [anon_sym_array] = ACTIONS(16),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      anon_sym_DQUOTE,
    ACTIONS(123), 1,
      anon_sym_LBRACK,
    ACTIONS(125), 1,
      sym_number,
    ACTIONS(48), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 2,
      sym_boolean,
      sym_string,
  [21] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 5,
      anon_sym_LBRACK,
      anon_sym_true,
      anon_sym_false,
      anon_sym_DQUOTE,
      sym_number,
  [32] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_identifier,
    ACTIONS(131), 1,
      anon_sym_RBRACE,
    STATE(35), 2,
      sym_member,
      aux_sym_object_repeat1,
  [46] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_identifier,
    ACTIONS(133), 1,
      anon_sym_RBRACE,
    STATE(34), 2,
      sym_member,
      aux_sym_object_repeat1,
  [60] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      sym_identifier,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
    STATE(28), 2,
      sym_member,
      aux_sym_object_repeat1,
  [74] = 4,
    ACTIONS(140), 1,
      anon_sym_DQUOTE,
    ACTIONS(144), 1,
      sym_comment,
    STATE(32), 1,
      aux_sym_string_repeat1,
    ACTIONS(142), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [88] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_identifier,
    ACTIONS(146), 1,
      anon_sym_RBRACE,
    STATE(28), 2,
      sym_member,
      aux_sym_object_repeat1,
  [102] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_LBRACK,
    ACTIONS(114), 3,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_identifier,
  [114] = 4,
    ACTIONS(144), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_DQUOTE,
    STATE(33), 1,
      aux_sym_string_repeat1,
    ACTIONS(152), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [128] = 4,
    ACTIONS(144), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_DQUOTE,
    STATE(33), 1,
      aux_sym_string_repeat1,
    ACTIONS(156), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [142] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_identifier,
    ACTIONS(159), 1,
      anon_sym_RBRACE,
    STATE(28), 2,
      sym_member,
      aux_sym_object_repeat1,
  [156] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_identifier,
    ACTIONS(161), 1,
      anon_sym_RBRACE,
    STATE(28), 2,
      sym_member,
      aux_sym_object_repeat1,
  [170] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_identifier,
    ACTIONS(163), 1,
      anon_sym_RBRACE,
    STATE(38), 2,
      sym_member,
      aux_sym_object_repeat1,
  [184] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_identifier,
    ACTIONS(165), 1,
      anon_sym_RBRACE,
    STATE(30), 2,
      sym_member,
      aux_sym_object_repeat1,
  [198] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_identifier,
    ACTIONS(167), 1,
      anon_sym_RBRACE,
    STATE(28), 2,
      sym_member,
      aux_sym_object_repeat1,
  [212] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 3,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_identifier,
  [221] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(169), 1,
      anon_sym_object,
    STATE(60), 1,
      sym_object,
  [234] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_SEMI,
    ACTIONS(171), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [245] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 3,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_identifier,
  [254] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 3,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_identifier,
  [263] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 3,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_identifier,
  [272] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 2,
      anon_sym_object,
      anon_sym_LBRACE,
  [280] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [288] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_LBRACK,
    ACTIONS(179), 1,
      anon_sym_LBRACE,
  [298] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_LBRACK,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
  [308] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_RBRACK,
  [315] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_LBRACK,
  [322] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_RBRACK,
  [329] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_RBRACK,
  [336] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      sym_number,
  [343] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
  [350] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      ts_builtin_sym_end,
  [357] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_LBRACK,
  [364] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      sym_number,
  [371] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_COLON,
  [378] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_LBRACK,
  [385] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(24)] = 0,
  [SMALL_STATE(25)] = 21,
  [SMALL_STATE(26)] = 32,
  [SMALL_STATE(27)] = 46,
  [SMALL_STATE(28)] = 60,
  [SMALL_STATE(29)] = 74,
  [SMALL_STATE(30)] = 88,
  [SMALL_STATE(31)] = 102,
  [SMALL_STATE(32)] = 114,
  [SMALL_STATE(33)] = 128,
  [SMALL_STATE(34)] = 142,
  [SMALL_STATE(35)] = 156,
  [SMALL_STATE(36)] = 170,
  [SMALL_STATE(37)] = 184,
  [SMALL_STATE(38)] = 198,
  [SMALL_STATE(39)] = 212,
  [SMALL_STATE(40)] = 221,
  [SMALL_STATE(41)] = 234,
  [SMALL_STATE(42)] = 245,
  [SMALL_STATE(43)] = 254,
  [SMALL_STATE(44)] = 263,
  [SMALL_STATE(45)] = 272,
  [SMALL_STATE(46)] = 280,
  [SMALL_STATE(47)] = 288,
  [SMALL_STATE(48)] = 298,
  [SMALL_STATE(49)] = 308,
  [SMALL_STATE(50)] = 315,
  [SMALL_STATE(51)] = 322,
  [SMALL_STATE(52)] = 329,
  [SMALL_STATE(53)] = 336,
  [SMALL_STATE(54)] = 343,
  [SMALL_STATE(55)] = 350,
  [SMALL_STATE(56)] = 357,
  [SMALL_STATE(57)] = 364,
  [SMALL_STATE(58)] = 371,
  [SMALL_STATE(59)] = 378,
  [SMALL_STATE(60)] = 385,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [7] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [10] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [16] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scalar, 2, 0, 5),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar, 2, 0, 5),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 6, 0, 3),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 6, 0, 3),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 5, 0, 6),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5, 0, 6),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 6, 0, 6),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 6, 0, 6),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 5, 0, 3),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5, 0, 3),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4, 0, 3),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 3),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_null, 1, 0, 0),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_null, 1, 0, 0), SHIFT(49),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member, 3, 0, 4),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 3, 0, 2),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member, 4, 0, 4),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [191] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 1),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_nya(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "nya",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
