name: CD

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true
          fetch-depth: 0

      - uses: ./.github/actions/setup
        with:
          llvm-version: 22

      - name: Build release targets
        run: ./build release
