/*
 * GENERATED by src/build/pp/lambda.c from the nya_lambda bodies in src/gnyame/layers/layer_pause_menu.c. DO NYAT EDIT.
 *
 * Included by that file and by nothing else: every function here is static, and each body was
 * written against whatever is in scope where the include sits. The bodies are copied through
 * character for character, so the #line above each one makes a diagnostic name the line and the
 * column somebody actually typed.
 */
#pragma once

#line 152 "src/gnyame/layers/layer_pause_menu.c"
NYA_INTERNAL void _nya_lambda_gny_locale_apply(void* data) {
                        u32 index = *(u32*)data;
                        nya_assert(index < nya_carray_length(_GNY_LOCALES));

                        NYA_Error loaded = nya_i18n_load(_GNY_LOCALES[index].locale, NYA_STRING_KEYS, NYA_STRING_COUNT);
                        if (!loaded.ok) nya_log_warn("Could not load '%s': %s", _GNY_LOCALES[index].locale, (NYA_ConstCString)loaded.message);
                    }
